# Copyright 2026 Vertel AB
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import fields, models


class PbxQueue(models.Model):
    _name = "pbx.queue"
    _inherit = ["pbx.plugin"]
    _description = "PBX Call Queue"

    tenant_id = fields.Many2one("pbx.tenant", required=True, ondelete="cascade")
    name = fields.Char(required=True)
    extension = fields.Char(required=True, help="Internal extension number for the queue")
    strategy = fields.Selection(
        [
            ("ringall", "Ring All"),
            ("leastrecent", "Least Recent"),
            ("fewestcalls", "Fewest Calls"),
            ("random", "Random"),
            ("rrmemory", "Round Robin Memory"),
            ("linear", "Linear"),
            ("wrandom", "Weighted Random"),
        ],
        default="ringall",
    )
    timeout = fields.Integer(default=60, help="Seconds before trying next agent")
    max_wait_time = fields.Integer(default=300, help="Max wait time before overflow")
    overflow_destination = fields.Char(help="Destination on overflow (extension, IVR, voicemail)")
    join_empty = fields.Boolean(default=True, help="Accept calls when no agents are logged in?")
    announce_position = fields.Boolean(default=False)
    is_ring_group = fields.Boolean(
        default=False,
        help="When True: strategy forced to ringall, timeout=0, no overflow. Simple ring group."
    )
    active = fields.Boolean(default=True)
    company_id = fields.Many2one(related="tenant_id.company_id", store=True)
    member_ids = fields.One2many("pbx.queue.member", "queue_id", string="Agents")

    def get_config_snippets(self, tenant):
        queues = self.search([("tenant_id", "=", tenant.id), ("active", "=", True)])
        if not queues:
            return {}
        return {"queues.conf": self._generate_queues_conf(queues)}

    def _generate_queues_conf(self, queues):
        lines = [f"; Auto-generated by pbx_queue — tenant: {queues[0].tenant_id.domain}"]
        for q in queues:
            strategy = "ringall" if q.is_ring_group else q.strategy
            timeout = 0 if q.is_ring_group else q.timeout
            lines.append(f"\n[{q.tenant_id.domain}-{q.name.lower().replace(' ', '-')}]")
            lines.append(f"strategy = {strategy}")
            lines.append(f"timeout = {timeout}")
            if not q.is_ring_group:
                lines.append(f"max-wait-time = {q.max_wait_time}")
                lines.append(f"joinempty = {'no' if not q.join_empty else 'yes'}")
            for member in q.member_ids.filtered(lambda m: m.extension_id.active):
                lines.append(
                    f"member => SIP/{q.tenant_id.domain}-{member.extension_id.public_number},{member.penalty}"
                )
        return "\n".join(lines)

    def get_fop2_widgets(self):
        return [{"name": "queue_panel", "component": "PbxQueuePanel", "props": {}}]


class PbxQueueMember(models.Model):
    _name = "pbx.queue.member"
    _description = "Queue Member (Agent)"

    queue_id = fields.Many2one("pbx.queue", required=True, ondelete="cascade")
    extension_id = fields.Many2one("pbx.extension", required=True, string="Agent Extension")
    penalty = fields.Integer(default=0, help="Lower = higher priority")
    paused = fields.Boolean(default=False)
    company_id = fields.Many2one(related="queue_id.company_id", store=True)
