{
    "name": "PBX Base",
    "version": "18.0.1.29.0",
    "summary": "Core PBX abstraction for multi-tenant Asterisk management",
    "category": "Productivity/VOIP",
    "author": "Vertel AB",
    "website": "https://github.com/vertelab/odoo-pbx",
    "license": "AGPL-3",
    "assets": {
        "web.assets_backend": [
            "pbx_base/static/src/click_to_call/click_to_call.js",
            "pbx_base/static/src/click_to_call/click_to_call.xml",
        ],
    },
    "web_icon": "static/description/icon.png",
    "depends": ["base", "mail", "resource", "voip_oca"],
    "data": [
        "security/pbx_security.xml",
        "security/ir.model.access.csv",
        "views/pbx_extension_views.xml",
        "views/pbx_trunk_views.xml",
        "views/pbx_inbound_route_views.xml",
        "views/pbx_outbound_route_views.xml",
        "views/res_company_views.xml",
        "views/res_config_settings_views.xml",
        "views/pbx_call_views.xml",
        "views/menus.xml",
        "views/pbx_device_template_views.xml",
    ],
    "installable": True,
    "application": False,
}
