version: "3.8"

services:
  odoo:
    image: odoo:18.0
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8069:8069"
    volumes:
      - .:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
      - ./docker/odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - pg-data:/var/lib/postgresql/data

  asterisk:
    image: andrius/asterisk:latest
    ports:
      - "5060:5060/udp"
      - "8089:8089"
    volumes:
      - asterisk-config:/etc/asterisk
      - asterisk-spool:/var/spool/asterisk
    environment:
      - ASTERISK_USER=pbx_admin
      - ASTERISK_SECRET=devsecret

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=pbx
      - RABBITMQ_DEFAULT_PASS=pbx
      - RABBITMQ_DEFAULT_VHOST=pbx

volumes:
  odoo-data:
  pg-data:
  asterisk-config:
  asterisk-spool:
