# Copyright 2026 Vertel AB
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import fields, models


class PbxRecordingPolicy(models.Model):
    _name = "pbx.recording.policy"
    _inherit = ["pbx.plugin"]
    _description = "PBX Recording Policy"

    tenant_id = fields.Many2one("res.partner", string="Tenant", required=True, ondelete="cascade", domain="[('is_pbx_tenant', '=', True)]")
    scope = fields.Selection(
        [("tenant", "Tenant"), ("queue", "Queue"), ("extension", "Extension")],
        required=True,
        default="tenant",
    )
    queue_id = fields.Many2one("pbx.queue", string="Queue")
    extension_id = fields.Many2one("pbx.extension", string="Extension")
    mode = fields.Selection(
        [("always", "Always"), ("never", "Never"), ("on_demand", "On Demand")],
        required=True,
        default="always",
    )
    active = fields.Boolean(default=True)
    company_id = fields.Many2one(related="tenant_id.company_id", store=True)

    def get_config_snippets(self, tenant):
        policies = self.search([("tenant_id", "=", tenant.id), ("active", "=", True)])
        if not policies:
            return {}
        return {"extensions_recording.conf": self._generate_recording_conf(policies)}

    def _generate_recording_conf(self, policies):
        domain = policies[0].tenant_id.domain
        lines = [f"; Auto-generated by pbx_recording — tenant: {domain}"]
        lines.append(f"\n[{domain}-recording]")
        lines.append(
            "exten => _X.,1,MixMonitor(${CDR(domain)}/${CDR(src)}_${CDR(dst)}_"
            "${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)}.wav,b)"
        )
        lines.append("same => n,Set(CDR(recording)=yes)")
        lines.append("same => n,Return()")
        return "\n".join(lines)

    def get_operator_panel_widgets(self):
        return [{"name": "recording_control", "component": "PbxRecordingControl", "props": {}}]

    def get_recording_widget_config(self):
        return {"mode": self.mode}

    def handle_recording_event(self, event_data):
        """Process a Recording.New event from RabbitMQ.
        Uploads .wav to Garage S3 via ir.attachment, links to voip.call.
        If pbx_ai is installed, triggers transcription."""
        file_path = event_data.get("file_path", "")
        call_id = event_data.get("call_id", 0)
        if not file_path:
            return

        call = self.env["voip.call"].browse(call_id)
        if not call.exists():
            return

        try:
            import base64
            with open(file_path, "rb") as f:
                audio_data = base64.b64encode(f.read())
            attachment = self.env["ir.attachment"].create({
                "name": f"Recording_{call.phone_number}_{call.create_date}",
                "datas": audio_data,
                "mimetype": "audio/wav",
                "res_model": "voip.call",
                "res_id": call.id,
            })

            # Trigger pbx_ai if available
            if self.env.registry.get("pbx.ai"):
                self.env["pbx.ai"].on_recording_ready(call, attachment)
        except (FileNotFoundError, OSError):
            pass
