# Copyright 2026 Vertel AB
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

import logging

from odoo import _, fields, models
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class PbxRecordingPolicy(models.Model):
    _name = "pbx.recording.policy"
    _inherit = ["pbx.plugin"]
    _description = "PBX Recording Policy"

    scope = fields.Selection(
        [("company", "Company"), ("extension", "Extension")],
        required=True,
        default="company",
    )
    extension = fields.Char(
        string="Extension",
        help="Internt nummer i inspelningsserien (8xx). Föreslås av 'Nästa lediga'.",
    )
    extension_id = fields.Many2one("pbx.extension", string="Extension")
    mode = fields.Selection(
        [("always", "Always"), ("never", "Never"), ("on_demand", "On Demand")],
        required=True,
        default="always",
    )
    active = fields.Boolean(default=True)
    company_id = fields.Many2one(
        "res.company", default=lambda self: self.env.company, required=True
    )

    def action_next_free_extension(self):
        """Föreslå nästa lediga nummer i inspelningsserien (8xx)."""
        self.ensure_one()
        number = self.env["pbx.numbering"]._next_free_service_number(
            self.company_id, "recording"
        )
        if not number:
            raise UserError(_("Inga lediga nummer i inspelningsserien."))
        self.extension = number
        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": _("Nästa lediga"),
                "message": _("Föreslår %s") % number,
                "type": "success",
                "sticky": False,
            },
        }

    def get_config_snippets(self, domain, company):
        policies = self.search([("company_id", "=", company.id), ("active", "=", True)])
        if not policies:
            return {}
        return {"extensions_recording.conf": self._generate_recording_conf(domain, policies)}

    def _generate_recording_conf(self, domain, policies):
        lines = [f"; Auto-generated by pbx_recording — domain: {domain}"]
        lines.append(f"\n[{domain}-recording]")
        lines.append(
            "exten => _X.,1,MixMonitor(${CDR(domain)}/${CDR(src)}_${CDR(dst)}_"
            "${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)}.wav,b)"
        )
        lines.append("same => n,Set(CDR(recording)=yes)")
        lines.append("same => n,Return()")
        return "\n".join(lines)

    def get_operator_panel_widgets(self):
        return [{"name": "recording_control", "component": "PbxRecordingControl", "props": {}}]

    def get_recording_widget_config(self):
        return {"mode": self.mode}

    def handle_recording_event(self, event_data):
        """Process a Recording.New event from RabbitMQ.

        Uploads .wav to Garage S3 via ir.attachment, links to pbx.call
        (recording_attachment_id). If pbx_ai is installed, triggers
        transcription (lokal transcriber via MQ-jobb).
        """
        file_path = event_data.get("file_path", "")
        call_id = event_data.get("call_id", 0)
        if not file_path:
            return

        # Samtalet är en pbx.call (Vertel) — fallback voip.call (OCA)
        call = self.env["pbx.call"].browse(call_id)
        call_model = "pbx.call"
        if not call.exists():
            call = self.env["voip.call"].browse(call_id)
            call_model = "voip.call"
        if not call.exists():
            return

        try:
            import base64
            with open(file_path, "rb") as f:
                audio_data = base64.b64encode(f.read())
            attachment = self.env["ir.attachment"].create({
                "name": f"Recording_{call.phone_number}_{call.create_date}",
                "datas": audio_data,
                "mimetype": "audio/wav",
                "res_model": call_model,
                "res_id": call.id,
            })

            # Koppla inspelningen explicit till samtalet (recording_attachment_id)
            if "recording_attachment_id" in call._fields:
                try:
                    call.write({"recording_attachment_id": attachment.id})
                except Exception as e:
                    _logger.warning("Kunde inte koppla inspelning: %s", e)

            # Trigger pbx_ai if available
            if self.env.registry.get("pbx.ai"):
                self.env["pbx.ai"].on_recording_ready(call, attachment)
        except (FileNotFoundError, OSError):
            pass
