{
    "name": "PBX Admin",
    "version": "18.0.1.0.1",
    "summary": "Central MSP panel for multi-tenant PBX management",
    "category": "Productivity/VOIP",
    "author": "Vertel AB",
    "website": "https://github.com/vertelab/odoo-pbx",
    "license": "AGPL-3",
    "depends": ["pbx_base"],
    "data": [
        "security/ir.model.access.csv",
        "security/pbx_admin_security.xml",
        "views/pbx_server_views.xml",
        "views/pbx_tenant_views.xml",
        "views/res_config_settings_views.xml",
        "views/pbx_tenant_admin_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": True,
}
