# Copyright 2026 Vertel AB
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import fields, models


class PbxIvr(models.Model):
    _name = "pbx.ivr"
    _inherit = ["pbx.plugin"]
    _description = "PBX IVR Menu"

    tenant_id = fields.Many2one("pbx.tenant", required=True, ondelete="cascade")
    name = fields.Char(required=True, help="e.g. Huvudmeny")
    extension = fields.Char(required=True, help="Internal extension for the IVR")
    greeting = fields.Many2one("ir.attachment", string="Greeting Audio")
    greeting_tts = fields.Text(string="TTS Greeting", help="Text-to-speech if no audio file")
    timeout = fields.Integer(default=5, help="Seconds for DTMF input")
    invalid_retries = fields.Integer(default=3)
    invalid_destination = fields.Char(help="Destination after max invalid retries")
    active = fields.Boolean(default=True)
    company_id = fields.Many2one(related="tenant_id.company_id", store=True)
    option_ids = fields.One2many("pbx.ivr.option", "ivr_id", string="Options")
    time_condition_id = fields.Many2one(
        "pbx.time_condition", string="Time Condition",
        help="First routing step: check time before IVR"
    )

    def get_config_snippets(self, tenant):
        ivrs = self.search([("tenant_id", "=", tenant.id), ("active", "=", True)])
        if not ivrs:
            return {}
        return {"extensions_ivr.conf": self._generate_ivr_conf(ivrs)}

    def _generate_ivr_conf(self, ivrs):
        lines = [f"; Auto-generated by pbx_ivr — tenant: {ivrs[0].tenant_id.domain}"]
        for ivr in ivrs:
            domain = ivr.tenant_id.domain
            lines.append(f"\n[{domain}-ivr-{ivr.name.lower().replace(' ', '-')}]")

            if ivr.time_condition_id:
                tc = ivr.time_condition_id
                lines.append(f"exten => s,1,GotoIfTime({self._format_time(tc.start_time)}-{self._format_time(tc.end_time)},{tc.days_of_week},*,*?matched)")
                lines.append(f"exten => s,n,Goto(no-match,s,1)")
                lines.append(f"exten => s,n(matched),Answer()")
            else:
                lines.append(f"exten => s,1,Answer()")

            lines.append(f"exten => s,n,Background({domain}-greeting-{ivr.name.lower().replace(' ', '-')})")
            lines.append(f"exten => s,n,WaitExten({ivr.timeout})")

            t_handled = False
            for opt in ivr.option_ids.sorted("sequence"):
                for lineno, line in enumerate(opt._get_destination_lines()):
                    lines.append(f"exten => {opt.digit},{lineno + 1},{line}")
                # Queue timeout → manuell hantering (UserEvent + routing)
                if opt.destination_type == "queue" and not t_handled:
                    q = self.env["pbx.queue"].search(
                        [("tenant_id", "=", ivr.tenant_id.id), ("name", "=", opt.destination)],
                        limit=1,
                    )
                    if q and q.timeout_seconds:
                        qname = f"{domain}-{q.name.lower().replace(' ', '-')}"
                        if q.timeout_action == "route_to_manual_queue" and q.manual_target_queue_id:
                            tq = q.manual_target_queue_id
                            tqname = f"{domain}-{tq.name.lower().replace(' ', '-')}"
                            lines.append(f"exten => t,1,UserEvent(ManualRequired,source=queue_timeout,queue={qname},target={tqname})")
                            lines.append(f"exten => t,n,Queue({tqname})")
                        elif q.timeout_action == "hangup":
                            lines.append(f"exten => t,1,Hangup()")
                        t_handled = True

            lines.append(f"exten => i,1,Playback(invalid)")
            lines.append(f"exten => i,n,Goto(s,1)")
            lines.append(f"exten => t,1,Goto({ivr.invalid_destination or 's,1'})")

            if ivr.time_condition_id:
                lines.append(f"exten => s,n(no-match),Goto({ivr.time_condition_id._get_destination_string(ivr.time_condition_id.destination_nomatch_type, ivr.time_condition_id.destination_nomatch_queue_id, ivr.time_condition_id.destination_nomatch_ivr_id, ivr.time_condition_id.destination_nomatch_extension_id, ivr.time_condition_id.destination_nomatch_external)},s,1)")

        return "\n".join(lines)

    @staticmethod
    def _format_time(hours_float):
        h = int(hours_float)
        m = int((hours_float - h) * 60)
        return f"{h:02d}:{m:02d}"

    def get_fop2_widgets(self):
        widgets = []
        ivrs = self.search(
            [("company_id", "=", self.env.user.company_id.id), ("active", "=", True)]
        )
        for ivr in ivrs:
            widgets.append(
                {
                    "name": f"ivr_panel_{ivr.id}",
                    "component": "PbxIvrPanel",
                    "props": {
                        "ivr": {
                            "key": ivr.extension,
                            "name": ivr.name,
                            "options": len(ivr.option_ids),
                        }
                    },
                }
            )
        return widgets


class PbxIvrOption(models.Model):
    _name = "pbx.ivr.option"
    _description = "IVR Menu Option"
    _order = "sequence"

    ivr_id = fields.Many2one("pbx.ivr", required=True, ondelete="cascade")
    digit = fields.Char(required=True, help="DTMF digit (0-9, *, #)")
    label = fields.Char(help="e.g. Support")
    destination_type = fields.Selection(
        [
            ("extension", "Extension"),
            ("queue", "Queue"),
            ("ivr", "Sub-IVR"),
            ("conference", "Conference"),
            ("voicemail", "Voicemail"),
            ("phonenumber", "External Number"),
        ],
        required=True,
        default="queue",
    )
    destination = fields.Char(required=True, help="Target extension, queue name, or external number")
    sequence = fields.Integer(default=10)

    def _get_destination_lines(self):
        """Return dialplan lines for this option.

        Supports UserEvent(ManualRequired) for manual/reception queues and
        the `t`-option for queues with a configured timeout.
        """
        domain = self.ivr_id.tenant_id.domain
        if self.destination_type == "extension":
            return [f"Dial(SIP/{domain}-{self.destination},30)", "Hangup()"]
        elif self.destination_type == "queue":
            q = self.env["pbx.queue"].search(
                [("tenant_id", "=", self.ivr_id.tenant_id.id), ("name", "=", self.destination)],
                limit=1,
            )
            qname = f"{domain}-{self.destination.lower().replace(' ', '-')}"
            lines = []
            if q and q.is_manual:
                lines.append(f"UserEvent(ManualRequired,source=ivr_reception,queue={qname})")
            queue_opt = ",t" if (q and q.timeout_seconds) else ""
            lines.append(f"Queue({qname}{queue_opt})")
            lines.append("Hangup()")
            return lines
        elif self.destination_type == "voicemail":
            return [f"Voicemail({self.destination}@{domain},u)", "Hangup()"]
        elif self.destination_type == "phonenumber":
            return [f"Dial(SIP/{self.destination}@trunk,30)", "Hangup()"]
        elif self.destination_type == "ivr":
            return [f"Goto({domain}-ivr-{self.destination.lower().replace(' ', '-')},s,1)"]
        elif self.destination_type == "conference":
            return [f"ConfBridge({domain}-{self.destination.lower().replace(' ', '-')})", "Hangup()"]
        return ["Hangup()"]
