# Copyright 2026 Vertel AB
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import api, fields, models

from odoo.addons.pbx_base.models.pbx_destination_mixin import DESTINATION_MODELS


class PbxIvr(models.Model):
    _name = "pbx.ivr"
    _inherit = ["pbx.plugin", "pbx.destination.mixin"]
    _description = "PBX IVR Menu"

    name = fields.Char(required=True, help="e.g. Huvudmeny")
    extension = fields.Char(required=True, help="Internal extension for the IVR")
    greeting = fields.Many2one("ir.attachment", string="Greeting Audio")
    greeting_tts = fields.Text(string="TTS Greeting", help="Text-to-speech if no audio file")
    timeout = fields.Integer(default=5, help="Seconds for DTMF input")
    invalid_retries = fields.Integer(default=3)
    invalid_destination_id = fields.Reference(
        selection=DESTINATION_MODELS,
        string="Invalid Destination",
        help="Destination after max invalid retries",
    )
    active = fields.Boolean(default=True)
    company_id = fields.Many2one(
        "res.company", string="Company", required=True,
        default=lambda self: self.env.company,
    )
    option_ids = fields.One2many("pbx.ivr.option", "ivr_id", string="Options")
    time_condition_id = fields.Many2one(
        "pbx.time_condition", string="Time Condition",
        help="First routing step: check time before IVR"
    )

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get("company_id") and vals.get("extension"):
                company = self.env["res.company"].browse(vals["company_id"])
                self.env["pbx.numbering"]._check_dialable_number(
                    company, vals["extension"]
                )
        return super().create(vals_list)

    def write(self, vals):
        if vals.get("extension") or vals.get("company_id"):
            for rec in self:
                company = (
                    self.env["res.company"].browse(vals["company_id"])
                    if vals.get("company_id")
                    else rec.company_id
                )
                number = vals.get("extension", rec.extension)
                self.env["pbx.numbering"]._check_dialable_number(
                    company, number, exclude=rec
                )
        return super().write(vals)

    def get_config_snippets(self, domain, company):
        ivrs = self.search([("company_id", "=", company), ("active", "=", True)])
        if not ivrs:
            return {}
        return {"extensions_ivr.conf": self._generate_ivr_conf(domain, ivrs)}

    def get_internal_dialplan(self, domain, company):
        """Make IVRs reachable by their internal extension number."""
        lines = []
        ivrs = self.search([("company_id", "=", company), ("active", "=", True)])
        for ivr in ivrs:
            lines.append(
                "exten => %s,1,Goto(%s-ivr-%s,s,1)"
                % (ivr.extension, domain, self._slug(ivr.name))
            )
        return "\n".join(lines)

    def get_dialplan_target(self):
        self.ensure_one()
        domain = self.company_id.pbx_domain or ""
        return ("%s-ivr-%s" % (domain, self._slug(self.name)), "s", "1")

    @staticmethod
    def _slug(name):
        return (name or "").lower().replace(" ", "-")

    def _generate_ivr_conf(self, domain, ivrs):
        lines = [f"; Auto-generated by pbx_ivr — domain: {domain}"]
        for ivr in ivrs:
            lines.append(f"\n[{domain}-ivr-{self._slug(ivr.name)}]")

            if ivr.time_condition_id:
                tc = ivr.time_condition_id
                lines.append(f"exten => s,1,GotoIfTime({self._format_time(tc.start_time)}-{self._format_time(tc.end_time)},{tc.days_of_week},*,*?matched)")
                lines.append(f"exten => s,n,Goto(no-match)")
                lines.append(f"exten => s,n(matched),Answer()")
            else:
                lines.append(f"exten => s,1,Answer()")

            lines.append(f"exten => s,n,Background({domain}-greeting-{self._slug(ivr.name)})")
            lines.append(f"exten => s,n,WaitExten({ivr.timeout})")

            t_handled = False
            for opt in ivr.option_ids.sorted("sequence"):
                for lineno, line in enumerate(opt._get_destination_lines()):
                    lines.append(f"exten => {opt.digit},{lineno + 1},{line}")
                # Queue timeout → manuell hantering (UserEvent + routing)
                queue_rec = opt._get_destination_record("pbx.queue")
                if queue_rec and queue_rec.timeout_seconds and not t_handled:
                    qname = f"{domain}-{self._slug(queue_rec.name)}"
                    if queue_rec.timeout_action == "route_to_manual_queue" and queue_rec.manual_target_queue_id:
                        tqname = f"{domain}-{self._slug(queue_rec.manual_target_queue_id.name)}"
                        lines.append(f"exten => t,1,UserEvent(ManualRequired,source=queue_timeout,queue={qname},target={tqname})")
                        lines.append(f"exten => t,n,Queue({tqname})")
                    elif queue_rec.timeout_action == "hangup":
                        lines.append(f"exten => t,1,Hangup()")
                    t_handled = True

            lines.append(f"exten => i,1,Playback(invalid)")
            lines.append(f"exten => i,n,Goto(s,1)")
            invalid_dest = self.env["pbx.destination.mixin"]._render_destination(
                ivr.invalid_destination_id
            )
            lines.append(f"exten => t,1,{invalid_dest}")

            if ivr.time_condition_id:
                tc = ivr.time_condition_id
                dest = self.env["pbx.destination.mixin"]._render_destination(
                    tc.destination_nomatch_id
                )
                lines.append(f"exten => s,n(no-match),{dest}")

        return "\n".join(lines)

    @staticmethod
    def _format_time(hours_float):
        h = int(hours_float)
        m = int(round((hours_float - h) * 60))
        return f"{h:02d}:{m:02d}"

    def get_operator_panel_widgets(self):
        widgets = []
        ivrs = self.search(
            [("company_id", "=", self.env.user.company_id.id), ("active", "=", True)]
        )
        for ivr in ivrs:
            widgets.append(
                {
                    "name": f"ivr_panel_{ivr.id}",
                    "component": "PbxIvrPanel",
                    "props": {
                        "ivr": {
                            "key": ivr.extension,
                            "name": ivr.name,
                            "options": len(ivr.option_ids),
                        }
                    },
                }
            )
        return widgets


class PbxIvrOption(models.Model):
    _name = "pbx.ivr.option"
    _description = "IVR Menu Option"
    _order = "sequence"

    ivr_id = fields.Many2one("pbx.ivr", required=True, ondelete="cascade")
    digit = fields.Char(required=True, help="DTMF digit (0-9, *, #)")
    label = fields.Char(help="e.g. Support")
    destination_id = fields.Reference(
        selection=DESTINATION_MODELS,
        string="Destination",
        required=True,
    )
    sequence = fields.Integer(default=10)

    def _get_destination_record(self, model=None):
        """Resolve the Reference destination to its record, optionally
        filtered by model (e.g. 'pbx.queue')."""
        if not self.destination_id:
            return None
        dest = self.destination_id
        if isinstance(dest, models.Model):
            record = dest
        else:
            m, _, rid = dest.partition(",")
            record = self.env[m].browse(int(rid))
        if model and record._name != model:
            return None
        return record

    def _get_destination_lines(self):
        """Return dialplan lines for this option.

        Queues keep their direct Queue() call (with UserEvent for manual
        queues and the `t` option for timeout handling in the IVR context);
        every other destination renders through the destination mixin as a
        single Goto() into its app context.
        """
        if not self.destination_id:
            return ["Hangup()"]
        record = self._get_destination_record()
        domain = self.company_id.pbx_domain or ""
        if record._name == "pbx.queue":
            qname = "%s-%s" % (domain, self.ivr_id._slug(record.name))
            lines = []
            if record.is_manual:
                lines.append(f"UserEvent(ManualRequired,source=ivr_reception,queue={qname})")
            queue_opt = ",t" if record.timeout_seconds else ""
            lines.append(f"Queue({qname}{queue_opt})")
            lines.append("Hangup()")
            return lines
        return [self.env["pbx.destination.mixin"]._render_destination(self.destination_id)]
