# Copyright 2026 Vertel AB
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

import base64
import io

from odoo import api, fields, models


class PbxSubExtensionProvisioning(models.Model):
    """Provisioning-stöd på pbx.sub_extension (pbx-provisioning).

    - Hardware (MAC): Yealink AutoP-konfiguration, per-tenant token
    - Desktop/Mobile (token): Linphone provisioning-XML
    """

    _inherit = "pbx.sub_extension"

    provisioning_url = fields.Char(
        string="Provisioning-URL",
        compute="_compute_provisioning_info",
        groups="pbx_base.group_pbx_admin",
        help="URL telefonen/appen hämtar sin konfiguration från.",
    )
    provisioning_qr = fields.Binary(
        string="Provisioning-QR",
        compute="_compute_provisioning_info",
        groups="pbx_base.group_pbx_admin",
        attachment=False,
        help="QR-kod med provisioning-URL:en (för onboarding/etikett).",
    )

    @api.depends(
        "type", "mac_address", "provisioning_token", "extension_id.company_id"
    )
    def _compute_provisioning_info(self):
        for rec in self:
            url = rec._get_provisioning_url()
            rec.provisioning_url = url
            rec.provisioning_qr = rec._qr_png(url) if url else False

    def _provisioning_base(self):
        """Bas-URL för provisioning (Caddy/Odoo), med scheman+tokens borttagna."""
        self.ensure_one()
        company = self.extension_id.company_id
        base = company.pbx_odoo_url or self.env["ir.config_parameter"].get_param(
            "web.base.url", "http://localhost"
        )
        return base.rstrip("/")

    def _get_provisioning_url(self):
        self.ensure_one()
        company = self.extension_id.company_id
        base = self._provisioning_base()
        if self.type == "hardware" and self.mac_address:
            company._ensure_pbx_provisioning_token()
            token = company.pbx_provisioning_token
            # Injicera credentials i URL:en: https://<domän>:<token>@host/...
            domain = company.pbx_domain or company.name or "tenant"
            from urllib.parse import urlsplit, urlunsplit

            parts = urlsplit(base)
            host = parts.netloc
            if "@" in host:
                host = host.rsplit("@", 1)[1]
            netloc = "%s:%s@%s" % (domain, token, host)
            base = urlunsplit((parts.scheme, netloc, parts.path, parts.query, parts.fragment))
            return "%s/pbx/provisioning/%s.cfg" % (base, self.mac_address)
        if self.type in ("desktop", "mobile") and self.provisioning_token:
            return "%s/pbx/provisioning/softphone/%s.xml" % (
                base, self.provisioning_token
            )
        return ""

    @staticmethod
    def _qr_png(url):
        """QR-kod som PNG-bytes (guarded import — modulen installeras även
        utan qrcode-paketet)."""
        try:
            import qrcode
        except ImportError:
            return False
        try:
            img = qrcode.make(url)
            buf = io.BytesIO()
            img.save(buf, format="PNG")
            return base64.b64encode(buf.getvalue())
        except Exception:
            return False

    # ------------------------------------------------------------------
    # Config-generering
    # ------------------------------------------------------------------

    def _yealink_transport_type(self):
        return {"udp": 0, "tcp": 1, "wss": 2}.get(self.transport, 0)

    def _get_yealink_config(self):
        """INI-konfig för Yealink AutoP (`account.1.*`)."""
        self.ensure_one()
        company = self.extension_id.company_id
        ext = self.extension_id
        display = ext.callerid_name or (ext.user_id.name if ext.user_id else "") or ext.public_number
        port = company.pbx_sip_port or ("5061" if self.transport == "wss" else "5060")
        lines = [
            "; Auto-generated by pbx_provisioning — Vertel",
            "account.1.enable = 1",
            "account.1.label = %s" % (self.label or ext.public_number),
            "account.1.display_name = %s" % display,
            "account.1.auth_name = %s" % self.username,
            "account.1.user_name = %s" % self.username,
            "account.1.password = %s" % self.secret,
            "account.1.sip_server.1.address = %s" % (company.pbx_server_host or "localhost"),
            "account.1.sip_server.1.port = %s" % port,
            "account.1.sip_server.1.transport_type = %d" % self._yealink_transport_type(),
        ]
        if company.pbx_stun_enabled and company.pbx_stun_server:
            lines.append("account.1.nat.nat_traversal = 1")
            lines.append("account.1.stun_server.active = 1")
            lines.append("account.1.stun_server.address = %s" % company.pbx_stun_server)
        return "\n".join(lines) + "\n"

    def _linphone_transport(self):
        return {"wss": "tls", "udp": "udp", "tcp": "tcp"}.get(self.transport, "udp")

    def _get_linphone_xml(self):
        """Linphone provisioning-XML (proxy_0/auth_info_0/misc)."""
        self.ensure_one()
        company = self.extension_id.company_id
        domain = company.pbx_domain or "localhost"
        server = company.pbx_server_host or "localhost"
        transport = self._linphone_transport()
        stun = ""
        if company.pbx_stun_enabled and company.pbx_stun_server:
            stun = (
                '  <section name="misc">\n'
                '    <entry name="stun_server">%s</entry>\n'
                "  </section>\n" % company.pbx_stun_server
            )
        return (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            "<config>\n"
            '  <section name="proxy_0">\n'
            '    <entry name="reg_identity">sip:%s@%s</entry>\n'
            '    <entry name="reg_proxy">sip:%s;transport=%s</entry>\n'
            '    <entry name="reg_sendregister">1</entry>\n'
            "  </section>\n"
            '  <section name="auth_info_0">\n'
            '    <entry name="username">%s</entry>\n'
            '    <entry name="passwd">%s</entry>\n'
            '    <entry name="domain">%s</entry>\n'
            "  </section>\n"
            "%s"
            "</config>\n"
        ) % (self.number, domain, server, transport, self.username, self.secret, domain, stun)
