{
    "name": "PBX AI Bridge",
    "version": "18.0.1.5.0",
    "summary": "PBX AI — transcript-dokument, receptionist-coworker, ARI",
    "category": "Productivity/VOIP",
    "author": "Vertel Sverige AB",
    "website": "https://github.com/vertelab/odoo-pbx",
    "license": "AGPL-3",
    "depends": [
        "pbx_tenant",
        "pbx_crm",
        "pbx_queue",
        "ai_agent_core",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/graph_definitions.xml",
        "data/pbx_tools.xml",
        "data/pbx_coworkers.xml",
        "data/pbx_activity_types.xml",
        "views/pbx_call_views.xml",
        "views/pbx_extension_views.xml",
        "views/pbx_queue_views.xml",
        "views/pbx_sub_extension_views.xml",
        "views/pbx_coworker_views.xml",
    ],
    "installable": True,
    "auto_install": False,
}
