# Copyright 2026 Vertel AB
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import fields, models


class PbxTimeCondition(models.Model):
    _name = "pbx.time_condition"
    _inherit = ["pbx.plugin"]
    _description = "PBX Time Condition"

    tenant_id = fields.Many2one("pbx.tenant", required=True, ondelete="cascade")
    name = fields.Char(required=True, help="e.g. Office Hours")
    timezone = fields.Char(default="Europe/Stockholm")
    days_of_week = fields.Char(
        default="mon-fri",
        help="Days: mon,tue,wed,thu,fri,sat,sun or ranges like mon-fri",
    )
    start_time = fields.Float(default=8.0, help="Start time (8.0 = 08:00)")
    end_time = fields.Float(default=17.0, help="End time (17.0 = 17:00)")
    holidays_calendar_id = fields.Many2one(
        "resource.calendar", string="Holiday Calendar",
    )

    # Destination when time matches
    destination_match_type = fields.Selection(
        [("queue", "Queue"), ("ivr", "IVR"), ("extension", "Extension"), ("voicemail", "Voicemail"), ("external", "External Number")],
        default="ivr",
        required=True,
    )
    destination_match_queue_id = fields.Many2one("pbx.queue", string="Match Queue")
    destination_match_ivr_id = fields.Many2one("pbx.ivr", string="Match IVR")
    destination_match_extension_id = fields.Many2one("pbx.extension", string="Match Extension")
    destination_match_external = fields.Char(string="Match External Number")

    # Destination when time does NOT match
    destination_nomatch_type = fields.Selection(
        [("queue", "Queue"), ("ivr", "IVR"), ("extension", "Extension"), ("voicemail", "Voicemail"), ("external", "External Number")],
        default="voicemail",
        required=True,
    )
    destination_nomatch_queue_id = fields.Many2one("pbx.queue", string="No-Match Queue")
    destination_nomatch_ivr_id = fields.Many2one("pbx.ivr", string="No-Match IVR")
    destination_nomatch_extension_id = fields.Many2one("pbx.extension", string="No-Match Extension")
    destination_nomatch_external = fields.Char(string="No-Match External Number")

    active = fields.Boolean(default=True)
    company_id = fields.Many2one(related="tenant_id.company_id", store=True)

    def _get_destination_string(self, dest_type, queue_id, ivr_id, extension_id, external):
        """Resolve destination type + reference to an Asterisk dialplan target."""
        domain = self.tenant_id.domain
        if dest_type == "queue" and queue_id:
            queue = self.env["pbx.queue"].browse(queue_id.id if hasattr(queue_id, 'id') else queue_id)
            return f"Queue({domain}-{queue.name.lower().replace(' ', '-')})"
        elif dest_type == "ivr" and ivr_id:
            ivr = self.env["pbx.ivr"].browse(ivr_id.id if hasattr(ivr_id, 'id') else ivr_id)
            return f"Goto({domain}-ivr-{ivr.name.lower().replace(' ', '-')},s,1)"
        elif dest_type == "extension" and extension_id:
            ext = self.env["pbx.extension"].browse(extension_id.id if hasattr(extension_id, 'id') else extension_id)
            return f"Dial(SIP/{domain}-{ext.public_number},30)"
        elif dest_type == "voicemail" and extension_id:
            ext = self.env["pbx.extension"].browse(extension_id.id if hasattr(extension_id, 'id') else extension_id)
            return f"Voicemail({ext.public_number}@{domain},u)"
        elif dest_type == "external" and external:
            return f"Dial(SIP/{external}@trunk,30)"
        return "Hangup()"

    def get_config_snippets(self, tenant):
        conditions = self.search([("tenant_id", "=", tenant.id), ("active", "=", True)])
        if not conditions:
            return {}
        return {"extensions_time.conf": self._generate_time_conf(conditions)}

    def _generate_time_conf(self, conditions):
        lines = [f"; Auto-generated by pbx_time_condition — tenant: {conditions[0].tenant_id.domain}"]
        for tc in conditions:
            domain = tc.tenant_id.domain
            dest_match = tc._get_destination_string(
                tc.destination_match_type,
                tc.destination_match_queue_id,
                tc.destination_match_ivr_id,
                tc.destination_match_extension_id,
                tc.destination_match_external,
            )
            dest_nomatch = tc._get_destination_string(
                tc.destination_nomatch_type,
                tc.destination_nomatch_queue_id,
                tc.destination_nomatch_ivr_id,
                tc.destination_nomatch_extension_id,
                tc.destination_nomatch_external,
            )
            lines.append(f"\n[{domain}-time-{tc.name.lower().replace(' ', '-')}]")
            lines.append(
                f"exten => s,1,GotoIfTime("
                f"{self._format_time(tc.start_time)}-{self._format_time(tc.end_time)},"
                f"{tc.days_of_week},*,*?matched)"
            )
            lines.append(f"exten => s,n,Goto(no-match,s,1)")
            lines.append(f"exten => s,n(matched),{dest_match}")
            lines.append(f"exten => s,n(no-match),{dest_nomatch}")
        return "\n".join(lines)

    @staticmethod
    def _format_time(hours_float):
        h = int(hours_float)
        m = int((hours_float - h) * 60)
        return f"{h:02d}:{m:02d}"

    def get_fop2_widgets(self):
        return [{"name": "time_condition_panel", "component": "PbxTimeConditionPanel", "props": {}}]
