# Copyright 2026 Vertel AB
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from datetime import timedelta

from odoo import fields, models

from odoo.addons.pbx_base.models.pbx_destination_mixin import destination_models


class PbxTimeCondition(models.Model):
    _name = "pbx.time_condition"
    _inherit = ["pbx.plugin", "pbx.destination.mixin"]
    _description = "PBX Time Condition"

    tenant_id = fields.Many2one("res.partner", string="Tenant", required=True, ondelete="cascade", domain="[('is_pbx_tenant', '=', True)]")
    name = fields.Char(required=True, help="e.g. Office Hours")
    timezone = fields.Char(default="Europe/Stockholm")
    days_of_week = fields.Char(
        default="mon-fri",
        help="Days: mon,tue,wed,thu,fri,sat,sun or ranges like mon-fri",
    )
    start_time = fields.Float(default=8.0, help="Start time (8.0 = 08:00)")
    end_time = fields.Float(default=17.0, help="End time (17.0 = 17:00)")
    holidays_calendar_id = fields.Many2one(
        "resource.calendar",
        string="Holiday Calendar",
        help="resource.calendar whose leaves are treated as no-match days",
    )

    # Polymorphic destinations (pbx.destination.mixin)
    destination_match_id = fields.Reference(
        selection=destination_models,
        string="Match Destination",
        required=True,
    )
    destination_nomatch_id = fields.Reference(
        selection=destination_models,
        string="No-Match Destination",
        required=True,
    )

    active = fields.Boolean(default=True)
    company_id = fields.Many2one(related="tenant_id.company_id", store=True)

    def get_dialplan_target(self):
        self.ensure_one()
        return ("%s-time-%s" % (self.tenant_id.domain, self._slug(self.name)), "s", "1")

    @staticmethod
    def _slug(name):
        return (name or "").lower().replace(" ", "-")

    def get_config_snippets(self, tenant):
        conditions = self.search([("tenant_id", "=", tenant.id), ("active", "=", True)])
        if not conditions:
            return {}
        return {"extensions_time.conf": self._generate_time_conf(conditions)}

    def _generate_time_conf(self, conditions):
        """GotoIfTime gate with holiday leaves rendered as no-match days."""
        lines = [
            "; Auto-generated by pbx_time_condition — tenant: %s"
            % conditions[0].tenant_id.domain
        ]
        for tc in conditions:
            domain = tc.tenant_id.domain
            dest_match = self.env["pbx.destination.mixin"]._render_destination(
                tc.destination_match_id
            )
            dest_nomatch = self.env["pbx.destination.mixin"]._render_destination(
                tc.destination_nomatch_id
            )
            lines.append("\n[%s-time-%s]" % (domain, self._slug(tc.name)))
            lines.append(
                "exten => s,1,GotoIfTime(%s-%s,%s,*,*?in-range)"
                % (
                    self._format_time(tc.start_time),
                    self._format_time(tc.end_time),
                    tc.days_of_week,
                )
            )
            lines.append("same => n,Goto(no-match)")
            lines.append("same => n(in-range),NoOp(Time matched)")
            for leave in tc.holidays_calendar_id.leave_ids:
                d_from = leave.date_from.date()
                d_to = leave.date_to.date()
                d = d_from
                while d <= d_to:
                    lines.append(
                        "same => n,GotoIfTime(00:00-23:59,%d,%d,%d?no-match)"
                        % (d.day, d.month, d.year)
                    )
                    d += timedelta(days=1)
            lines.append("same => n,%s" % dest_match)
            lines.append("same => n(no-match),%s" % dest_nomatch)
        return "\n".join(lines)

    @staticmethod
    def _format_time(hours_float):
        h = int(hours_float)
        m = int(round((hours_float - h) * 60))
        return "%02d:%02d" % (h, m)

    def get_operator_panel_widgets(self):
        return [{"name": "time_condition_panel", "component": "PbxTimeConditionPanel", "props": {}}]


class PbxOutboundRoute(models.Model):
    """Tillägg på outbound-route när pbx_time_condition är installerat."""

    _inherit = "pbx.outbound_route"

    time_condition_id = fields.Many2one(
        "pbx.time_condition",
        string="Time Condition",
        help="Used when time_source = Time Condition",
    )
