# Copyright 2026 Vertel AB
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

import logging

from odoo import models

_logger = logging.getLogger(__name__)

PJSIP_TEMPLATE = """\
; Auto-generated by pbx_base — tenant: {domain}
; DO NOT EDIT MANUALLY

[{domain}-endpoint](!)
type = endpoint
context = {domain}-internal
disallow = all
allow = ulaw,alaw,g722,opus
direct_media = no

[{domain}-aor](!)
type = aor
max_contacts = 10
remove_existing = yes

[{domain}-identify]
type = identify
match = {domain}
endpoint = {domain}-endpoint

; --- Extensions ---
{extensions}

; --- Templates ---
[{domain}-auth](!)
type = auth
auth_type = userpass
"""

EXTENSION_TEMPLATE = """\
[{domain}-{number}]
type = endpoint
context = {domain}-internal
auth = {domain}-{number}-auth
aors = {domain}-{number}
callerid = "{callerid_name}" <{public_number}@{domain}>

[{domain}-{number}-auth]({domain}-auth)
password = {secret}
username = {username}
"""

EXTENSIONS_CONF_TEMPLATE = """\
; Auto-generated by pbx_base — tenant: {domain}
; DO NOT EDIT MANUALLY

[{domain}-internal]
exten => _X.,1,NoOp(Incoming call to {domain})
same => n,Hangup()

; --- Ring Groups ---
{ring_groups}

; --- Voicemail ---
{voicemail_routes}
"""

RING_GROUP_TEMPLATE = """\
exten => {public_number},1,NoOp(Ring group for {public_number})
exten => {public_number},n,Dial({dial_string},30)
exten => {public_number},n,Voicemail({public_number}@{domain},u)
exten => {public_number},n,Hangup()
"""

VOICEMAIL_CONF_TEMPLATE = """\
; Auto-generated by pbx_base — tenant: {domain}
; DO NOT EDIT MANUALLY

[{domain}]
{mailboxes}
"""

MAILBOX_TEMPLATE = "{public_number} => {pin},{callerid_name},,,attach=yes|maxmsg={max_messages}|maxsecs={max_duration}|delete=yes"


class PbxConfigGenerator(models.AbstractModel):
    _name = "pbx.config.generator"
    _description = "PBX Config Generator"

    def generate_pjsip(self, tenant):
        """Generate pjsip.conf for a tenant."""
        extensions = self.env["pbx.extension"].search(
            [("tenant_id", "=", tenant.id), ("active", "=", True)]
        )
        ext_blocks = []
        for ext in extensions:
            for sub in ext.sub_extension_ids.filtered(
                lambda s: s.active and s.type != "voicemail"
            ):
                ext_blocks.append(
                    EXTENSION_TEMPLATE.format(
                        domain=tenant.domain,
                        number=sub.number,
                        public_number=ext.public_number,
                        callerid_name=ext.callerid_name or ext.user_id.name or "",
                        username=sub.username,
                        secret=sub.secret,
                    )
                )

        return PJSIP_TEMPLATE.format(
            domain=tenant.domain,
            extensions="\n".join(ext_blocks) if ext_blocks else "",
        )

    def generate_extensions(self, tenant):
        """Generate extensions.conf dialplan for a tenant."""
        extensions = self.env["pbx.extension"].search(
            [("tenant_id", "=", tenant.id), ("active", "=", True)]
        )
        ring_groups = []
        voicemail_routes = []

        for ext in extensions:
            active_subs = ext.sub_extension_ids.filtered(
                lambda s: s.active and s.type != "voicemail"
            )
            if not active_subs:
                continue

            if ext.ring_strategy == "parallel":
                dial_string = "&".join(
                    f"SIP/{tenant.domain}-{sub.number}" for sub in active_subs
                )
            else:
                dial_string = "&".join(
                    f"SIP/{tenant.domain}-{sub.number}"
                    for sub in active_subs.sorted("priority")
                )

            ring_groups.append(
                RING_GROUP_TEMPLATE.format(
                    public_number=ext.public_number,
                    domain=tenant.domain,
                    dial_string=dial_string,
                )
            )

        return EXTENSIONS_CONF_TEMPLATE.format(
            domain=tenant.domain,
            ring_groups="\n".join(ring_groups) if ring_groups else "",
            voicemail_routes="\n".join(voicemail_routes) if voicemail_routes else "",
        )

    def generate_voicemail(self, tenant):
        """Generate voicemail.conf for a tenant."""
        extensions = self.env["pbx.extension"].search(
            [("tenant_id", "=", tenant.id), ("active", "=", True)]
        )
        mailboxes = []
        for ext in extensions:
            voicemail_sub = ext.sub_extension_ids.filtered(
                lambda s: s.active and s.type == "voicemail"
            )
            if voicemail_sub:
                sub = voicemail_sub[0]
                mailboxes.append(
                    MAILBOX_TEMPLATE.format(
                        public_number=ext.public_number,
                        pin=ext.public_number,  # Default PIN = extension number
                        callerid_name=ext.callerid_name or ext.user_id.name or "",
                        max_messages=sub.max_messages,
                        max_duration=sub.max_duration,
                    )
                )

        return VOICEMAIL_CONF_TEMPLATE.format(
            domain=tenant.domain,
            mailboxes="\n".join(mailboxes) if mailboxes else "",
        )

    def generate_all(self, tenant):
        """Generate all config files for a tenant, including plugin snippets."""
        configs = {
            "pjsip_wizard.conf": self.generate_pjsip(tenant),
            "extensions.conf": self.generate_extensions(tenant),
            "voicemail.conf": self.generate_voicemail(tenant),
        }

        # Collect plugin snippets
        plugins = self.env["pbx.plugin"].search([])
        for plugin in plugins:
            snippets = plugin.get_config_snippets(tenant)
            for filename, content in snippets.items():
                if filename in configs:
                    configs[filename] += "\n" + content
                else:
                    configs[filename] = content

        return configs

    def write_config(self, tenant):
        """Deploy generated config to the Asterisk server via RabbitMQ.

        The pbx_ami_daemon consumes `pbx.config.<domain>` and writes the
        files to /etc/asterisk/tenants/ then reloads Asterisk.
        Falls back to local disk when MQ is not configured (dev).
        """
        configs = self.generate_all(tenant)
        mq = self.env["pbx.mq.publisher"]
        if mq.publish_config(tenant, configs):
            _logger.info("Deployed config via MQ for tenant %s", tenant.domain)
            return True
        return self.write_config_local(tenant, configs)

    def write_config_local(self, tenant, configs=None):
        """Write generated config files to local disk (dev fallback)."""
        server = tenant.server_id
        if configs is None:
            configs = self.generate_all(tenant)
        tenant_dir = f"{server.config_path}/tenants/{tenant.domain}"

        # Create directory if needed
        import os

        os.makedirs(tenant_dir, exist_ok=True)

        for filename, content in configs.items():
            filepath = f"{tenant_dir}/{filename}"
            with open(filepath, "w") as f:
                f.write(content)
            _logger.info("Wrote config: %s for tenant %s", filepath, tenant.domain)

        return True

    def reload_asterisk(self, server):
        """Reload Asterisk configuration via AMI."""
        import socket

        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(5)
            sock.connect((server.host, server.ami_port))

            # Login
            sock.recv(1024)  # Read banner
            sock.sendall(
                f"Action: Login\r\nUsername: {server.ami_user}\r\nSecret: {server.ami_secret}\r\n\r\n".encode()
            )
            response = sock.recv(1024).decode()
            if "Success" not in response:
                _logger.error("AMI login failed for %s", server.host)
                return False

            # Reload
            sock.sendall(b"Action: Command\r\nCommand: pjsip reload\r\n\r\n")
            sock.recv(1024)
            sock.sendall(b"Action: Command\r\nCommand: dialplan reload\r\n\r\n")
            sock.recv(1024)
            sock.sendall(b"Action: Command\r\nCommand: voicemail reload\r\n\r\n")
            sock.recv(1024)
            sock.sendall(b"Action: Logoff\r\n\r\n")
            sock.close()

            _logger.info("Asterisk reloaded for server %s", server.host)
            return True
        except Exception as e:
            _logger.error("AMI reload failed: %s", e)
            return False
