# Copyright 2026 Vertel AB
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

import logging
import re
from datetime import timedelta

from odoo import api, fields, models

_logger = logging.getLogger(__name__)

PJSIP_TEMPLATE = """\
; Auto-generated by pbx_base — domain: {domain}
; DO NOT EDIT MANUALLY

[{domain}-endpoint](!)
type = endpoint
context = {domain}-internal
disallow = all
direct_media = no

[{domain}-aor](!)
type = aor
max_contacts = 10
remove_existing = yes

[{domain}-auth](!)
type = auth
auth_type = userpass

; --- Extensions ---
{extensions}

; --- Trunks ---
{trunks}
"""

EXTENSION_TEMPLATE = """\
[{username}]({domain}-endpoint)
type = endpoint
context = {domain}-internal
transport = transport-{transport}
{webrtc_options}
{nat_options}
auth = {domain}-{number}-auth
aors = {username}
callerid = "{callerid_name}" <{public_number}@{domain}>
{codec_allows}

[{domain}-{number}-auth]({domain}-auth)
password = {secret}
username = {username}

[{username}]({domain}-aor)
type = aor
"""

# WebRTC/DTLS options for wss endpoints (verified against Asterisk 20.6):
# media_encryption = dtls (not dtls_srtp — invalid in 20.6), ice_support,
# use_avpf (required for the RTP/SAVPF offer), rtcp_mux (required by Chrome/Edge),
# dtls_cert/private_key + dtls_verify = no.
WEBRTC_OPTIONS_TEMPLATE = """\
media_encryption = dtls
ice_support = yes
use_avpf = yes
rtcp_mux = yes
dtls_cert_file = {cert_file}
dtls_private_key = {private_key}
dtls_verify = no"""

TRUNK_TEMPLATE = """\
[{domain}-trunk-{slug}]
type = endpoint
context = {domain}-from-trunk
disallow = all
{codec_allows}
outbound_auth = {domain}-trunk-{slug}-auth
aors = {domain}-trunk-{slug}-aor
callerid = "{callerid}"

[{domain}-trunk-{slug}-auth]
type = auth
auth_type = userpass
username = {username}
password = {secret}

[{domain}-trunk-{slug}-aor]
type = aor
contact = sip:{host}:{port}
{registration}
{identify}"""

# Registration-based trunk (inbound without a public port-forward): providers
# such as Telavox reach the box via received:port — the AOR needs no static port.
REGISTRATION_TEMPLATE = """\
[{domain}-trunk-{slug}-reg]
type = registration
server_uri = sip:{host}:{port}
client_uri = sip:{username}@{host}
contact_user = {username}
outbound_auth = {domain}-trunk-{slug}-auth
"""

IDENTIFY_TEMPLATE = """\
[{domain}-trunk-{slug}-identify]
type = identify
match = {ip}
endpoint = {domain}-trunk-{slug}
"""

EXTENSIONS_CONF_TEMPLATE = """\
; Auto-generated by pbx_base — domain: {domain}
; DO NOT EDIT MANUALLY

[{domain}-internal]
{internal_entries}
{outbound_entry}
exten => _X.,1,NoOp(Unknown extension in {domain})
same => n,Playback(invalid)
same => n,Hangup()

; --- Extension ring-group contexts ---
{ext_contexts}

; --- Voicemail contexts ---
{vm_contexts}

; --- Inbound routes (DID/CID -> destination) ---
{inbound_context}

; --- Outbound routes ---
{outbound_context}
"""

EXT_CONTEXT_TEMPLATE = """\
[{domain}-ext-{public_number}]
exten => s,1,NoOp(Ring group for {public_number})
{busy_gates}{availability_gates}{dial_lines}{follow_me_fallback}same => n,Hangup()
same => n(done),Hangup()
same => n(busy),Voicemail({public_number}@{domain},b)
same => n,Hangup()
{availability_announcement}"""

# Announcement played when the person is unavailable (outside work hours or
# busy in the calendar): "the person is back at HH:MM" via SayUnixTime, then
# voicemail. OC_AVAIL is set by the availability gate: "ok:<ts>" | "busy:<ts>".
AVAILABILITY_ANNOUNCEMENT_TEMPLATE = """\
same => n(unavailable),NoOp(Person unavailable — next ${{CUT(OC_AVAIL,:,2)}})
same => n,GotoIf($["${{CUT(OC_AVAIL,:,2)}}" = "0"]?unavail_noannounce)
same => n,SayUnixTime(${{CUT(OC_AVAIL,:,2)}},,%H:%M)
same => n(unavail_noannounce),Voicemail({public_number}@{domain},u)
same => n,Hangup()
"""

VM_CONTEXT_TEMPLATE = """\
[{domain}-vm-{public_number}]
exten => s,1,Voicemail({public_number}@{domain},u)
"""

VOICEMAIL_CONF_TEMPLATE = """\
; Auto-generated by pbx_base — domain: {domain}
; DO NOT EDIT MANUALLY

[{domain}]
{mailboxes}
"""

# Mailbox options for file-based voicemail: NO attach=yes/delete=yes —
# delete=yes makes notify_new_message delete the message from INBOX immediately
# (designed for email/IMAP setups); without email the recording disappears.
# attach=yes has no effect without email_/imap_ configuration.
MAILBOX_TEMPLATE = "{public_number} => {pin},{callerid_name},,,maxmsg={max_messages}|maxsecs={max_duration}"

# GotoIfTime days-of-week map: resource.calendar.attendance.dayofweek is
# '0'..'6' with 0 = Monday (Odoo resource convention).
_DAY_NAMES = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]


class PbxConfigGenerator(models.AbstractModel):
    _name = "pbx.config.generator"
    _description = "PBX Config Generator"

    # ------------------------------------------------------------------
    # pjsip
    # ------------------------------------------------------------------
    def _codec_allows(self, company, sub=None):
        """Codec allow lines for an endpoint.

        The device's codec rows (sequence order) → otherwise the global default
        (active + supported, priority order). Browser (Odoo VOIP) always
        requires opus (WebRTC).
        """
        names = []
        if sub and sub.codec_ids:
            names = sub.codec_ids.sorted("sequence").mapped("codec_id.name")
            if sub.type == "browser" and "opus" not in names:
                names = ["opus"] + names
        else:
            codecs = self.env["pbx.codec"].search(
                [("active", "=", True), ("supported", "=", True)]
            )
            names = codecs.sorted("priority").mapped("name")
        return "\n".join("allow = %s" % name for name in names)

    @api.model
    def _webrtc_options(self):
        """DTLS/ICE/AVPF options for WebRTC (wss) endpoints.

        The DTLS certificate paths can be overridden via ir.config_parameter
        (pbx.dtls.cert_file / pbx.dtls.private_key) — the default matches the
        salt-deployed Asterisk.
        """
        ICP = self.env["ir.config_parameter"].sudo()
        return WEBRTC_OPTIONS_TEMPLATE.format(
            cert_file=ICP.get_param(
                "pbx.dtls.cert_file",
                "/etc/asterisk/keys/asterisk-sip-cert.pem",
            ),
            private_key=ICP.get_param(
                "pbx.dtls.private_key",
                "/etc/asterisk/keys/asterisk-sip-key.pem",
            ),
        )

    def generate_pjsip(self, domain, company):
        """Generate pjsip.conf for the instance's own domain."""
        extensions = self.env["pbx.extension"].search(
            [("company_id", "=", self._company_id(company)), ("active", "=", True)]
        )
        ext_blocks = []
        for ext in extensions:
            for sub in ext.sub_extension_ids.filtered(
                lambda s: s.active and s.type != "voicemail"
            ):
                ext_blocks.append(
                    EXTENSION_TEMPLATE.format(
                        domain=domain,
                        number=sub.number,
                        public_number=ext.public_number,
                        callerid_name=ext.callerid_name or ext.user_id.name or "",
                        username=sub.username,
                        secret=ext.password or sub.secret,
                        transport=sub.transport or "udp",
                        webrtc_options=(
                            self._webrtc_options() if sub.type == "browser" else ""
                        ),
                        nat_options=(
                            ""
                            if sub.type == "browser"
                            else (
                                "rewrite_contact = yes\n"
                                "force_rport = yes\n"
                                "rtp_symmetric = yes"
                            )
                        ),
                        codec_allows=self._codec_allows(company, sub),
                    )
                )

        trunks = self.env["pbx.trunk"].search(
            [("company_id", "=", self._company_id(company)), ("active", "=", True)]
        )
        trunk_blocks = []
        for trunk in trunks:
            slug = self._slug(trunk.name)
            # NOTE: external_media_address/external_signaling_address are
            # TRANSPORT options in chan_pjsip — they are set in the transport
            # section (pjsip.conf, salt-owned), not per endpoint. They used to
            # live in the endpoint section and made the whole endpoint fail:
            # "Could not find option suitable for category '…-trunk-…'
            #  named 'external_media_address'" → no calls in/out.
            # Registration: registration-based inbound (without a static port)
            registration = ""
            if trunk.username and trunk.host:
                registration = "\n" + REGISTRATION_TEMPLATE.format(
                    domain=domain,
                    slug=slug,
                    username=trunk.username,
                    host=trunk.host,
                    port=trunk.port or 5060,
                )
            # Identify: an explicit field wins; otherwise DNS lookup on the host
            # (no hardcoding — the IP is fetched dynamically at generation time)
            identify = ""
            identify_ip = (trunk.identify_ip or "").strip()
            if not identify_ip and trunk.host:
                try:
                    import socket

                    identify_ip = socket.gethostbyname(trunk.host)
                except OSError:
                    identify_ip = ""
            if identify_ip:
                identify = "\n" + IDENTIFY_TEMPLATE.format(
                    domain=domain, slug=slug, ip=identify_ip
                )
            trunk_blocks.append(
                TRUNK_TEMPLATE.format(
                    domain=domain,
                    slug=slug,
                    username=trunk.username or "",
                    secret=trunk.secret or "",
                    host=trunk.host,
                    port=trunk.port or 5060,
                    callerid=trunk.callerid or "",
                    codec_allows=self._codec_allows(company),
                    registration=registration,
                    identify=identify,
                )
            )

        return PJSIP_TEMPLATE.format(
            domain=domain,
            extensions="\n".join(ext_blocks) if ext_blocks else "",
            trunks="\n".join(trunk_blocks) if trunk_blocks else "",
        )

    # ------------------------------------------------------------------
    # extensions.conf
    # ------------------------------------------------------------------
    @staticmethod
    def _company_id(company):
        """Return the res.company id whether a recordset or int is passed."""
        return company.id if isinstance(company, models.Model) else company

    @staticmethod
    def _slug(name):
        """URL-safe slug of a trunk name for use in object names."""
        slug = re.sub(r"[^a-zA-Z0-9_-]", "", name or "").lower()
        return slug or "trunk"

    @staticmethod
    def _format_time(hour_float):
        """resource.calendar hour (8.0, 17.5) → '08:00' / '17:30' for GotoIfTime."""
        h = int(hour_float)
        m = int(round((hour_float - h) * 60))
        if m == 60:
            h += 1
            m = 0
        return "%02d:%02d" % (h, m)

    def generate_extensions(self, domain, company):
        """Generate the instance dialplan: internal dialing, ring groups,
        voicemail contexts, inbound routes and outbound routes."""
        extensions = self.env["pbx.extension"].search(
            [("company_id", "=", self._company_id(company)), ("active", "=", True)]
        )
        internal_entries = []
        ext_contexts = []
        vm_contexts = []

        for ext in extensions:
            entry = self._get_extension_internal_entry(ext, domain)
            if entry:
                # Plugin-provided internal entry (e.g. AI extension → Stasis).
                internal_entries.append(entry)
                continue
            active_subs = ext.sub_extension_ids.filtered(
                lambda s: s.active and s.type != "voicemail"
            )
            if not active_subs:
                continue
            internal_entries.append(
                "exten => %s,1,Goto(%s-ext-%s,s,1)"
                % (ext.public_number, domain, ext.public_number)
            )

            # Build busy gates (DEVICE_STATE check per active sub).
            # Always: if the user is talking on any of their phones → voicemail.
            busy_gates = ""
            for sub in active_subs:
                busy_gates += (
                    'same => n,GotoIf($["${{DEVICE_STATE(PJSIP/{username})}}"'
                    ' = "INUSE"]?busy)\n'
                ).format(username=sub.username)

            # Build dial lines
            dial_lines = ""
            if ext.ring_strategy == "parallel":
                dial_peers = "&".join(
                    "PJSIP/%s" % sub.username
                    for sub in active_subs.sorted("sequence")
                )
                max_timeout = max(sub.ring_timeout or 30 for sub in active_subs)
                dial_lines = "same => n,Dial(%s,%d)\n" % (dial_peers, max_timeout)
            else:
                sorted_subs = active_subs.sorted("sequence")
                for i, sub in enumerate(sorted_subs):
                    to = sub.ring_timeout or 30
                    dial_lines += (
                        "same => n,Dial(PJSIP/{username},{timeout})\n"
                    ).format(username=sub.username, timeout=to)
                    if i + 1 < len(sorted_subs):
                        # Not format-ed — single braces so ${DIALSTATUS} ends up
                        # correct in the output (double braces would become ${{DIALSTATUS}})
                        dial_lines += (
                            'same => n,GotoIf($["${DIALSTATUS}"'
                            ' != "NOANSWER"]?done)\n'
                        )

            # Availability gate (respect_schedule/respect_calendar)
            availability_gates = self._availability_gates(ext, company)
            availability_announcement = self._availability_announcement(
                domain, ext.public_number, bool(availability_gates)
            )

            # Follow-me fallback: AI destination (plugin) or voicemail.
            follow_me_fallback = self._follow_me_fallback(ext, domain)

            ext_contexts.append(
                EXT_CONTEXT_TEMPLATE.format(
                    domain=domain,
                    public_number=ext.public_number,
                    busy_gates=busy_gates,
                    availability_gates=availability_gates,
                    dial_lines=dial_lines,
                    follow_me_fallback=follow_me_fallback,
                    availability_announcement=availability_announcement,
                )
            )
            vm_sub = ext.sub_extension_ids.filtered(
                lambda s: s.active and s.type == "voicemail"
            )
            if vm_sub:
                vm_contexts.append(
                    VM_CONTEXT_TEMPLATE.format(
                        domain=domain, public_number=ext.public_number
                    )
                )

        # Internal dialing contributed by plugins (queues, IVRs, conferences)
        for plugin in self._get_plugin_recordsets():
            snippet = plugin.get_internal_dialplan(domain, company)
            if snippet:
                internal_entries.append(snippet)

        # Feature codes + operator-0 (pbx-numbering) in the internal context
        feature_entries = self.env["pbx.numbering"]._feature_code_entries(
            domain, company
        )
        if feature_entries:
            internal_entries.append(feature_entries)

        # Outbound entry from the internal context (0 + number, or +46,
        # -> outbound). Goto to ${EXTEN} (not s,1) — the outbound context
        # has no s-extensions, only patterns matching the dialled
        # number.
        outbound_entry = ""
        if self.env["pbx.outbound_route"].search_count(
            [("company_id", "=", self._company_id(company)), ("active", "=", True)]
        ):
            outbound_entry = (
                "exten => _0.,1,Goto(%s-outbound,${EXTEN},1)\n" % domain
                + "exten => _+.,1,Goto(%s-outbound,${EXTEN},1)\n" % domain
            )
            # E.164 without '+' (46725020525) → normalise to +46… before outbound
            outbound_entry += (
                "exten => _46XXXXXXXX.,1,Set(DIAL_NUMBER=+${EXTEN})\n"
                "same => n,Goto(%s-outbound,${DIAL_NUMBER},1)\n" % domain
            )

        inbound_context = self._generate_inbound_context(domain, company)
        outbound_context = self._generate_outbound_context(domain, company)

        return EXTENSIONS_CONF_TEMPLATE.format(
            domain=domain,
            internal_entries="\n".join(internal_entries) if internal_entries else "",
            outbound_entry=outbound_entry,
            ext_contexts="\n".join(ext_contexts) if ext_contexts else "",
            vm_contexts="\n".join(vm_contexts) if vm_contexts else "",
            inbound_context=inbound_context,
            outbound_context=outbound_context,
        )

    # ------------------------------------------------------------------
    # Inbound routes: {domain}-from-trunk
    # ------------------------------------------------------------------
    def _generate_inbound_context(self, domain, company):
        """Emit [domain-from-trunk] with DID/CID matches sorted by sequence.

        Routes are grouped by their match expression so that multiple
        CID-only routes chain on the same `_.` extension; the fallback
        plays ss-noservice when no catch-all route exists.
        """
        routes = self.env["pbx.inbound_route"].search(
            [("company_id", "=", self._company_id(company)), ("active", "=", True)],
            order="sequence, id",
        )
        if not routes:
            return ""
        lines = ["[%s-from-trunk]" % domain]

        groups = []
        group_map = {}
        for route in routes:
            match = self._inbound_match(route)
            if match not in group_map:
                group_map[match] = []
                groups.append((match, group_map[match]))
            group_map[match].append(route)

        for match, group_routes in groups:
            for idx, route in enumerate(group_routes):
                label = "r%s" % route.sequence
                desc = route.description or match
                if idx == 0:
                    lines.append("exten => %s,1,NoOp(Inbound: %s)" % (match, desc))
                else:
                    lines.append(
                        "same => n(%s-start),NoOp(Inbound: %s)" % (label, desc)
                    )
                if route.cid and not route.did:
                    # CID-only route: match any DID, filter by caller ID
                    next_label = self._inbound_next_label(group_routes, idx)
                    lines.append(
                        'same => n,GotoIf($["${CALLERID(num)}" = "%s"]?%s)'
                        % (route.cid, label)
                    )
                    lines.append("same => n,Goto(%s)" % next_label)
                    lines.append("same => n(%s),Set(__FROM_DID=${EXTEN})" % label)
                else:
                    lines.append(
                        "same => n,Set(__FROM_DID=%s)" % self._inbound_did_var(route)
                    )
                dest = self.env["pbx.destination.mixin"]._render_destination(
                    route.destination_id
                )
                lines.append("same => n,%s" % dest)

        has_catchall = any(not r.did and not r.cid for r in routes)
        if not has_catchall:
            lines.append("exten => s,1,NoOp(No DID or CID match)")
            lines.append("same => n,Playback(ss-noservice)")
            lines.append("same => n,Hangup()")
            # Unmatched DIDs with no explicit CID-only chain are also caught
            if not any(r.cid and not r.did for r in routes):
                lines.append("exten => _.,1,NoOp(No DID or CID match)")
                lines.append("same => n,Playback(ss-noservice)")
                lines.append("same => n,Hangup()")

        # Trunk account-name alias: some providers (e.g. Telavox) send
        # inbound calls with the ACCOUNT NAME (trunk.username) as the called party
        # instead of the DID. Trunks with inbound_destination_id get their own
        # exten for the account name → the destination.
        for trunk in self.env["pbx.trunk"].search(
            [("company_id", "=", self._company_id(company)), ("active", "=", True)]
        ):
            if not (trunk.username and trunk.inbound_destination_id):
                continue
            dest = self.env["pbx.destination.mixin"]._render_destination(
                trunk.inbound_destination_id
            )
            lines.append("exten => %s,1,NoOp(Inbound trunk account: %s)" % (
                trunk.username, trunk.username,
            ))
            lines.append("same => n,Set(__FROM_DID=${EXTEN})")
            lines.append("same => n,%s" % dest)

        return "\n".join(lines)

    @staticmethod
    def _inbound_match(route):
        if route.did and route.cid:
            return "%s/%s" % (route.did, route.cid)
        if route.did:
            return route.did
        if route.cid:
            return "_."
        return "s"

    @staticmethod
    def _inbound_did_var(route):
        if route.did and route.cid:
            return route.did
        return "${EXTEN}"

    @staticmethod
    def _inbound_next_label(group_routes, idx):
        if idx + 1 < len(group_routes):
            return "r%s-start" % group_routes[idx + 1].sequence
        return "s,1"

    # ------------------------------------------------------------------
    # Outbound routes: {domain}-outbound
    # ------------------------------------------------------------------
    def _generate_outbound_context(self, domain, company):
        """Emit [domain-outbound] with pattern chains + trunk failover.

        Routes sharing a pattern chain on one exten (sequence order); each
        route gets an optional time gate, number manipulation, ordered trunk
        failover and a shared failover context when everything fails.
        """
        routes = self.env["pbx.outbound_route"].search(
            [("company_id", "=", self._company_id(company)), ("active", "=", True)],
            order="sequence, id",
        )
        if not routes:
            return ""
        failover_ctx = "%s-outbound-failover" % domain
        lines = ["[%s-outbound]" % domain]

        groups = []
        group_map = {}
        for route in routes:
            if route.pattern not in group_map:
                group_map[route.pattern] = []
                groups.append((route.pattern, group_map[route.pattern]))
            group_map[route.pattern].append(route)

        for pattern, chain in groups:
            for idx, route in enumerate(chain):
                seq = route.sequence
                if idx == 0:
                    lines.append("exten => %s,1,NoOp(Outbound: %s)" % (pattern, route.name))
                else:
                    lines.append(
                        "same => n(r%s-start),NoOp(Outbound: %s)" % (seq, route.name)
                    )
                if idx + 1 < len(chain):
                    next_label = "r%s-start" % chain[idx + 1].sequence
                else:
                    next_label = "%s,failover,1" % failover_ctx
                gate = self._route_time_gate(route, "r%s-go" % seq, next_label)
                if gate:
                    lines.extend(gate)
                else:
                    lines.append("same => n,Goto(r%s-go)" % seq)
                strip = route.strip_digits or 0
                num = "${EXTEN}" if not strip else "${EXTEN:%d}" % strip
                dial_number = "%s%s" % (route.prepend_digits or "", num)
                lines.append(
                    "same => n(r%s-go),Set(DIAL_NUMBER=%s)" % (seq, dial_number)
                )
                trunks = route.trunk_ids.sorted("sequence")
                for tidx, rt in enumerate(trunks):
                    lines.append(
                        "same => n,Dial(PJSIP/${DIAL_NUMBER}@%s-trunk-%s,60,tT)"
                        % (domain, self._slug(rt.trunk_id.name))
                    )
                    lines.append(
                        'same => n,GotoIf($["${DIALSTATUS}" = "ANSWER"]?%s,hangup,1)'
                        % failover_ctx
                    )
                    if tidx + 1 < len(trunks):
                        if rt.continue_:
                            lines.append("same => n,Goto(r%s-t%d)" % (seq, tidx + 1))
                        else:
                            lines.append(
                                "same => n,Goto(%s,failover,1)" % failover_ctx
                            )
                        lines.append(
                            "same => n(r%s-t%d),NoOp(Trunk failover to next)"
                            % (seq, tidx + 1)
                        )
                    else:
                        lines.append("same => n,Goto(%s,failover,1)" % failover_ctx)

        # Shared failover context: every trunk/route failed
        failover = self._outbound_failover(self.env, routes)
        lines.append("")
        lines.append("[%s]" % failover_ctx)
        lines.append("exten => failover,1,NoOp(All trunks failed)")
        lines.append("same => n,%s" % failover)
        lines.append("exten => hangup,1,Hangup()")
        return "\n".join(lines)

    def _route_time_gate(self, route, match_label, miss_label):
        """Return dialplan lines gating a route by time, or [] if ungated.

        Holidays (resource.calendar.leaves) always skip to miss_label;
        attendance/time-condition matches jump to match_label.
        """
        if (
            route.time_source == "time_condition"
            and "time_condition_id" in route._fields
            and route.time_condition_id
        ):
            tc = route.time_condition_id
            lines = self._holiday_skip_lines(tc.holidays_calendar_id, miss_label)
            lines.append(
                "same => n,GotoIfTime(%s-%s,%s,*,*?%s)"
                % (
                    self._format_time(tc.start_time),
                    self._format_time(tc.end_time),
                    tc.days_of_week,
                    match_label,
                )
            )
            lines.append("same => n,Goto(%s)" % miss_label)
            return lines
        if route.time_source == "calendar" and route.calendar_id:
            cal = route.calendar_id
            lines = self._holiday_skip_lines(cal, miss_label)
            for att in cal.attendance_ids.sorted("dayofweek"):
                lines.append(
                    "same => n,GotoIfTime(%s-%s,%s,*,*?%s)"
                    % (
                        self._format_time(att.hour_from),
                        self._format_time(att.hour_to),
                        _DAY_NAMES[int(att.dayofweek)],
                        match_label,
                    )
                )
            lines.append("same => n,Goto(%s)" % miss_label)
            return lines
        return []

    @staticmethod
    def _holiday_skip_lines(calendar, miss_label):
        """GotoIfTime per leave day — holidays skip to miss_label."""
        lines = []
        if not calendar:
            return lines
        for leave in calendar.leave_ids:
            d_from = leave.date_from.date()
            d_to = leave.date_to.date()
            d = d_from
            while d <= d_to:
                lines.append(
                    "same => n,GotoIfTime(00:00-23:59,%d,%d,%d?%s)"
                    % (d.day, d.month, d.year, miss_label)
                )
                d += timedelta(days=1)
        return lines

    @staticmethod
    def _outbound_failover(env, routes):
        """Dialplan executed when every route/trunk fails.

        Uses the last route's failover destination; otherwise congestion.
        """
        last = routes[-1]
        if last.failover_destination_id:
            return env["pbx.destination.mixin"]._render_destination(
                last.failover_destination_id
            )
        return "Playback(all-circuits-busy-now&please-try-call-later)"

    # ------------------------------------------------------------------
    # voicemail.conf
    # ------------------------------------------------------------------
    def generate_voicemail(self, domain, company):
        """Generate voicemail.conf for the instance."""
        extensions = self.env["pbx.extension"].search(
            [("company_id", "=", self._company_id(company)), ("active", "=", True)]
        )
        mailboxes = []
        for ext in extensions:
            voicemail_sub = ext.sub_extension_ids.filtered(
                lambda s: s.active and s.type == "voicemail"
            )
            if voicemail_sub:
                sub = voicemail_sub[0]
                mailboxes.append(
                    MAILBOX_TEMPLATE.format(
                        public_number=ext.public_number,
                        pin=ext.public_number,  # Default PIN = extension number
                        callerid_name=ext.callerid_name or ext.user_id.name or "",
                        max_messages=sub.max_messages,
                        max_duration=sub.max_duration,
                    )
                )

        return VOICEMAIL_CONF_TEMPLATE.format(
            domain=domain,
            mailboxes="\n".join(mailboxes) if mailboxes else "",
        )

    def _get_plugin_recordsets(self):
        """Yield one recordset per concrete record implementing pbx.plugin.

        pbx.plugin is an AbstractModel with no table — plugins must be
        collected by scanning the registry for models inheriting it.

        Plugins are configured as regular records (recording policies, time
        conditions, queues, conferences, ...). A plugin model whose table is
        empty contributes nothing, so empty recordsets are skipped: the base
        implementation calls ensure_one(), which would raise ValueError on an
        empty recordset and abort the whole config generation.
        """
        for model_name, model in self.env.registry.items():
            if model._abstract:
                continue
            inherits = model._inherit or []
            if isinstance(inherits, str):
                inherits = [inherits]
            if "pbx.plugin" not in inherits:
                continue
            records = self.env[model_name].search([])
            if not records:
                continue
            for record in records:
                yield record

    # ------------------------------------------------------------------
    # Orchestration
    # ------------------------------------------------------------------
    def _availability_gates(self, ext, company):
        """CURL check of Odoo availability before follow-me ringing.

        Only emitted when the extension respects schedule/calendar AND an Odoo
        URL is configured. The endpoint returns ``ok:<ts>`` or ``busy:<ts>``;
        on CURL failure the variable is empty → the call proceeds (fail-open).
        """
        if not (ext.respect_schedule or ext.respect_calendar):
            return ""
        if isinstance(company, models.Model):
            company_rec = company
        else:
            company_rec = self.env["res.company"].browse(company)
        odoo_url = company_rec.pbx_odoo_url or self.env["ir.config_parameter"].get_param(
            "web.base.url", ""
        )
        if not odoo_url:
            return ""
        token = self.env["ir.config_parameter"].get_param("pbx.webhook.token", "")
        return ext._render_availability_gate(odoo_url=odoo_url, webhook_token=token)

    def _availability_announcement(self, domain, public_number, active=False):
        """Label block reached via the availability gate when unavailable."""
        if not active:
            return ""
        return AVAILABILITY_ANNOUNCEMENT_TEMPLATE.format(
            domain=domain, public_number=public_number
        )

    def _follow_me_fallback(self, ext, domain):
        """Dialplan line after the devices have been rung without answer.

        If the extension has an AI follow-me destination (field from pbx_ai)
        the call is routed to Stasis(coworker,<id>); otherwise voicemail.
        """
        ai_coworker = False
        if "follow_me_ai_coworker_id" in self.env["pbx.extension"]._fields:
            ai_coworker = ext.follow_me_ai_coworker_id
        if ai_coworker and ai_coworker.active and ai_coworker._get_leader_agent():
            return (
                "same => n,Stasis(coworker,%s)\n" % ai_coworker.id)
        return (
            "same => n,Voicemail({public_number}@{domain},u)\n").format(
            public_number=ext.public_number, domain=domain)

    def _get_extension_internal_entry(self, ext, domain):
        """Return the internal dialplan entry for an extension, or None.

        Default: None → the caller falls back to the standard entry
        ``Goto(domain-ext-<num>,s,1)`` (the ring group). Plugins can override
        this hook to deliver their own entry (e.g. AI extension →
        Stasis(coworker,<id>)).
        """
        return None

    def generate_all(self, domain, company):
        """Generate all config files for the instance, incl. plugin snippets."""
        configs = {
            "pjsip_wizard.conf": self.generate_pjsip(domain, company),
            "extensions.conf": self.generate_extensions(domain, company),
            "voicemail.conf": self.generate_voicemail(domain, company),
        }

        # Collect plugin snippets
        for plugin in self._get_plugin_recordsets():
            snippets = plugin.get_config_snippets(domain, company)
            for filename, content in snippets.items():
                if filename in configs:
                    configs[filename] += "\n" + content
                else:
                    configs[filename] = content

        return configs

    def write_config(self, domain, company):
        """Deploy generated config to the Asterisk server via RabbitMQ.

        The pbx_ami_daemon consumes `pbx.config.<domain>` and writes the
        files to /etc/asterisk/tenants/ then reloads Asterisk.

        Returns the published version (int) on success, False on failure.
        Records the version on the company — `config_dirty` stays True
        until the daemon acks the version as applied (pbx-freepbx-core).
        """
        configs = self.generate_all(domain, company)
        mq = self.env["pbx.mq.publisher"]
        version = mq.publish_config(domain, configs)
        if version:
            company_rec = (
                company
                if isinstance(company, models.Model)
                else self.env["res.company"].browse(company)
            )
            company_rec.write(
                {
                    "pbx_config_version": version,
                    "pbx_config_sync_error": False,
                }
            )
            _logger.info("Deployed config via MQ for domain %s (version %s)", domain, version)
            return version
        _logger.warning("MQ not configured — config not deployed for %s", domain)
        return False

    @api.model
    def get_sync_state(self):
        """Current sync state for the user's company (used by the systray).

        can_sync = self-service for all internal users (base.group_user +
        superuser). Calling res.users.has_group via RPC does not work
        (has_group is @api.readonly and call_kw interprets the string as ids) —
        therefore can_sync is computed here server-side.

        state: clean | sent | applied | error (res.company.pbx_config_sync_state).
        """
        company = self.env.company
        return {
            "dirty": bool(company.config_dirty),
            "domain": company.pbx_domain or "",
            "can_sync": self.env.user._is_internal(),
            "state": company.pbx_config_sync_state or "clean",
            "version": company.pbx_config_version or 0,
            "applied_version": company.pbx_config_applied_version or 0,
            "error": company.pbx_config_sync_error or "",
        }

    @api.model
    def sync_current_company(self):
        """Deploy config for the current user's company to Asterisk.

        Only internal users (self-service) may trigger a sync. Returns a dict
        with ok/message for the UI notification; marks the company clean on success.
        """
        if not self.env.user._is_internal():
            return {
                "ok": False,
                "message": "Only internal users can sync the configuration.",
            }
        company = self.env.company
        domain = company.pbx_domain
        if not domain:
            return {
                "ok": False,
                "message": "Configuration error: no SIP domain set for the company (Settings → PBX).",
            }
        ok = self.write_config(domain, company)
        if ok:
            return {
                "ok": True,
                "message": "Configuration sent to Asterisk for %s (version %s). "
                "Waiting for confirmation…" % (domain, ok),
            }
        return {
            "ok": False,
            "message": "Configuration error: could not send for %s — check the RabbitMQ settings (Settings → PBX)."
            % domain,
        }
