# Copyright 2026 Vertel AB
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

import logging
from datetime import timedelta

from odoo import fields, models

_logger = logging.getLogger(__name__)

PJSIP_TEMPLATE = """\
; Auto-generated by pbx_base — domain: {domain}
; DO NOT EDIT MANUALLY

[{domain}-endpoint](!)
type = endpoint
context = {domain}-internal
disallow = all
allow = ulaw,alaw,g722,opus
direct_media = no

[{domain}-aor](!)
type = aor
max_contacts = 10
remove_existing = yes

[{domain}-identify]
type = identify
match = {domain}
endpoint = {domain}-endpoint

; --- Extensions ---
{extensions}

; --- Trunks ---
{trunks}

; --- Templates ---
[{domain}-auth](!)
type = auth
auth_type = userpass
"""

EXTENSION_TEMPLATE = """\
[{domain}-{number}]
type = endpoint
context = {domain}-internal
auth = {domain}-{number}-auth
aors = {domain}-{number}
callerid = "{callerid_name}" <{public_number}@{domain}>

[{domain}-{number}-auth]({domain}-auth)
password = {secret}
username = {username}
"""

TRUNK_TEMPLATE = """\
[{domain}-trunk-{slug}](!)
type = endpoint
context = {domain}-from-trunk
disallow = all
allow = ulaw,alaw
outbound_auth = {domain}-trunk-{slug}-auth
aors = {domain}-trunk-{slug}
callerid = "{callerid}"

[{domain}-trunk-{slug}-auth]
type = auth
auth_type = userpass
username = {username}
password = {secret}

[{domain}-trunk-{slug}-aor]
type = aor
contact = sip:{host}:{port}
"""

EXTENSIONS_CONF_TEMPLATE = """\
; Auto-generated by pbx_base — domain: {domain}
; DO NOT EDIT MANUALLY

[{domain}-internal]
{internal_entries}
{outbound_entry}
exten => _X.,1,NoOp(Unknown extension in {domain})
same => n,Playback(invalid)
same => n,Hangup()

; --- Extension ring-group contexts ---
{ext_contexts}

; --- Voicemail contexts ---
{vm_contexts}

; --- Inbound routes (DID/CID -> destination) ---
{inbound_context}

; --- Outbound routes ---
{outbound_context}
"""

EXT_CONTEXT_TEMPLATE = """\
[{domain}-ext-{public_number}]
exten => s,1,NoOp(Ring group for {public_number})
{busy_gates}{availability_gates}{dial_lines}same => n,Voicemail({public_number}@{domain},u)
same => n,Hangup()
same => n(done),Hangup()
same => n(busy),Voicemail({public_number}@{domain},b)
same => n,Hangup()
{availability_announcement}"""

# Announcement played when the person is unavailable (outside work hours or
# busy in the calendar): "personen är tillbaka HH:MM" via SayUnixTime, then
# voicemail. OC_AVAIL is set by the availability gate: "ok:<ts>" | "busy:<ts>".
AVAILABILITY_ANNOUNCEMENT_TEMPLATE = """\
same => n(unavailable),NoOp(Person unavailable — next ${CUT(OC_AVAIL,:,2)})
same => n,GotoIf($["${{CUT(OC_AVAIL,:,2)}}" = "0"]?unavail_noannounce)
same => n,SayUnixTime(${{CUT(OC_AVAIL,:,2)}},,%H:%M)
same => n(unavail_noannounce),Voicemail({public_number}@{domain},u)
same => n,Hangup()
"""

VM_CONTEXT_TEMPLATE = """\
[{domain}-vm-{public_number}]
exten => s,1,Voicemail({public_number}@{domain},u)
"""

VOICEMAIL_CONF_TEMPLATE = """\
; Auto-generated by pbx_base — domain: {domain}
; DO NOT EDIT MANUALLY

[{domain}]
{mailboxes}
"""

MAILBOX_TEMPLATE = "{public_number} => {pin},{callerid_name},,,attach=yes|maxmsg={max_messages}|maxsecs={max_duration}|delete=yes"

# GotoIfTime days-of-week map: resource.calendar.attendance.dayofweek is
# '0'..'6' with 0 = Monday (Odoo resource convention).
_DAY_NAMES = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]


class PbxConfigGenerator(models.AbstractModel):
    _name = "pbx.config.generator"
    _description = "PBX Config Generator"

    # ------------------------------------------------------------------
    # pjsip
    # ------------------------------------------------------------------
    def generate_pjsip(self, domain, company):
        """Generate pjsip.conf for the instance's own domain."""
        extensions = self.env["pbx.extension"].search(
            [("company_id", "=", company), ("active", "=", True)]
        )
        ext_blocks = []
        for ext in extensions:
            for sub in ext.sub_extension_ids.filtered(
                lambda s: s.active and s.type != "voicemail"
            ):
                ext_blocks.append(
                    EXTENSION_TEMPLATE.format(
                        domain=domain,
                        number=sub.number,
                        public_number=ext.public_number,
                        callerid_name=ext.callerid_name or ext.user_id.name or "",
                        username=sub.username,
                        secret=ext.password or sub.secret,
                    )
                )

        trunks = self.env["pbx.trunk"].search(
            [("company_id", "=", company), ("active", "=", True)]
        )
        trunk_blocks = []
        for trunk in trunks:
            trunk_blocks.append(
                TRUNK_TEMPLATE.format(
                    domain=domain,
                    slug=self._slug(trunk.name),
                    username=trunk.username or "",
                    secret=trunk.secret or "",
                    host=trunk.host,
                    port=trunk.port or 5060,
                    callerid=trunk.callerid or "",
                )
            )

        return PJSIP_TEMPLATE.format(
            domain=domain,
            extensions="\n".join(ext_blocks) if ext_blocks else "",
            trunks="\n".join(trunk_blocks) if trunk_blocks else "",
        )

    # ------------------------------------------------------------------
    # extensions.conf
    # ------------------------------------------------------------------
    def generate_extensions(self, domain, company):
        """Generate the instance dialplan: internal dialing, ring groups,
        voicemail contexts, inbound routes and outbound routes."""
        extensions = self.env["pbx.extension"].search(
            [("company_id", "=", company), ("active", "=", True)]
        )
        internal_entries = []
        ext_contexts = []
        vm_contexts = []

        for ext in extensions:
            active_subs = ext.sub_extension_ids.filtered(
                lambda s: s.active and s.type != "voicemail"
            )
            if not active_subs:
                continue
            internal_entries.append(
                "exten => %s,1,Goto(%s-ext-%s,s,1)"
                % (ext.public_number, domain, ext.public_number)
            )

            # Build busy gates (DEVICE_STATE check per active sub)
            busy_gates = ""
            if ext.skip_if_busy:
                for sub in active_subs:
                    busy_gates += (
                        'same => n,GotoIf($["${{DEVICE_STATE(PJSIP/{domain}-{number})}}"'
                        ' = "INUSE"]?busy)\n'
                    ).format(domain=domain, number=sub.number)

            # Build dial lines
            dial_lines = ""
            if ext.ring_strategy == "parallel":
                dial_peers = "&".join(
                    "PJSIP/%s-%s" % (domain, sub.number)
                    for sub in active_subs.sorted("sequence")
                )
                max_timeout = max(sub.ring_timeout or 30 for sub in active_subs)
                dial_lines = "same => n,Dial(%s,%d)\n" % (dial_peers, max_timeout)
            else:
                sorted_subs = active_subs.sorted("sequence")
                for i, sub in enumerate(sorted_subs):
                    to = sub.ring_timeout or 30
                    dial_lines += (
                        "same => n,Dial(PJSIP/{domain}-{number},{timeout})\n"
                    ).format(domain=domain, number=sub.number, timeout=to)
                    if i + 1 < len(sorted_subs):
                        dial_lines += (
                            'same => n,GotoIf($["${{DIALSTATUS}}"'
                            ' != "NOANSWER"]?done)\n'
                        )

            # Availability gate (respect_schedule/respect_calendar)
            availability_gates = self._availability_gates(ext, company)
            availability_announcement = self._availability_announcement(
                domain, ext.public_number, bool(availability_gates)
            )

            ext_contexts.append(
                EXT_CONTEXT_TEMPLATE.format(
                    domain=domain,
                    public_number=ext.public_number,
                    busy_gates=busy_gates,
                    availability_gates=availability_gates,
                    dial_lines=dial_lines,
                    availability_announcement=availability_announcement,
                )
            )
            vm_sub = ext.sub_extension_ids.filtered(
                lambda s: s.active and s.type == "voicemail"
            )
            if vm_sub:
                vm_contexts.append(
                    VM_CONTEXT_TEMPLATE.format(
                        domain=domain, public_number=ext.public_number
                    )
                )

        # Internal dialing contributed by plugins (queues, IVRs, conferences)
        for plugin in self._get_plugin_recordsets():
            snippet = plugin.get_internal_dialplan(domain, company)
            if snippet:
                internal_entries.append(snippet)

        # Outbound entry from the internal context (0 + number -> outbound)
        outbound_entry = ""
        if self.env["pbx.outbound_route"].search_count(
            [("company_id", "=", company), ("active", "=", True)]
        ):
            outbound_entry = "exten => _0.,1,Goto(%s-outbound,s,1)\n" % domain

        inbound_context = self._generate_inbound_context(domain, company)
        outbound_context = self._generate_outbound_context(domain, company)

        return EXTENSIONS_CONF_TEMPLATE.format(
            domain=domain,
            internal_entries="\n".join(internal_entries) if internal_entries else "",
            outbound_entry=outbound_entry,
            ext_contexts="\n".join(ext_contexts) if ext_contexts else "",
            vm_contexts="\n".join(vm_contexts) if vm_contexts else "",
            inbound_context=inbound_context,
            outbound_context=outbound_context,
        )

    # ------------------------------------------------------------------
    # Inbound routes: {domain}-from-trunk
    # ------------------------------------------------------------------
    def _generate_inbound_context(self, domain, company):
        """Emit [domain-from-trunk] with DID/CID matches sorted by sequence.

        Routes are grouped by their match expression so that multiple
        CID-only routes chain on the same `_.` extension; the fallback
        plays ss-noservice when no catch-all route exists.
        """
        routes = self.env["pbx.inbound_route"].search(
            [("company_id", "=", company), ("active", "=", True)],
            order="sequence, id",
        )
        if not routes:
            return ""
        lines = ["[%s-from-trunk]" % domain]

        groups = []
        group_map = {}
        for route in routes:
            match = self._inbound_match(route)
            if match not in group_map:
                group_map[match] = []
                groups.append((match, group_map[match]))
            group_map[match].append(route)

        for match, group_routes in groups:
            for idx, route in enumerate(group_routes):
                label = "r%s" % route.sequence
                desc = route.description or match
                if idx == 0:
                    lines.append("exten => %s,1,NoOp(Inbound: %s)" % (match, desc))
                else:
                    lines.append(
                        "same => n(%s-start),NoOp(Inbound: %s)" % (label, desc)
                    )
                if route.cid and not route.did:
                    # CID-only route: match any DID, filter by caller ID
                    next_label = self._inbound_next_label(group_routes, idx)
                    lines.append(
                        'same => n,GotoIf($["${CALLERID(num)}" = "%s"]?%s)'
                        % (route.cid, label)
                    )
                    lines.append("same => n,Goto(%s)" % next_label)
                    lines.append("same => n(%s),Set(__FROM_DID=${EXTEN})" % label)
                else:
                    lines.append(
                        "same => n,Set(__FROM_DID=%s)" % self._inbound_did_var(route)
                    )
                dest = self.env["pbx.destination.mixin"]._render_destination(
                    route.destination_id
                )
                lines.append("same => n,%s" % dest)

        has_catchall = any(not r.did and not r.cid for r in routes)
        if not has_catchall:
            lines.append("exten => s,1,NoOp(No DID or CID match)")
            lines.append("same => n,Playback(ss-noservice)")
            lines.append("same => n,Hangup()")
            # Unmatched DIDs with no explicit CID-only chain are also caught
            if not any(r.cid and not r.did for r in routes):
                lines.append("exten => _.,1,NoOp(No DID or CID match)")
                lines.append("same => n,Playback(ss-noservice)")
                lines.append("same => n,Hangup()")

        return "\n".join(lines)

    @staticmethod
    def _inbound_match(route):
        if route.did and route.cid:
            return "%s/%s" % (route.did, route.cid)
        if route.did:
            return route.did
        if route.cid:
            return "_."
        return "s"

    @staticmethod
    def _inbound_did_var(route):
        if route.did and route.cid:
            return route.did
        return "${EXTEN}"

    @staticmethod
    def _inbound_next_label(group_routes, idx):
        if idx + 1 < len(group_routes):
            return "r%s-start" % group_routes[idx + 1].sequence
        return "s,1"

    # ------------------------------------------------------------------
    # Outbound routes: {domain}-outbound
    # ------------------------------------------------------------------
    def _generate_outbound_context(self, domain, company):
        """Emit [domain-outbound] with pattern chains + trunk failover.

        Routes sharing a pattern chain on one exten (sequence order); each
        route gets an optional time gate, number manipulation, ordered trunk
        failover and a shared failover context when everything fails.
        """
        routes = self.env["pbx.outbound_route"].search(
            [("company_id", "=", company), ("active", "=", True)],
            order="sequence, id",
        )
        if not routes:
            return ""
        failover_ctx = "%s-outbound-failover" % domain
        lines = ["[%s-outbound]" % domain]

        groups = []
        group_map = {}
        for route in routes:
            if route.pattern not in group_map:
                group_map[route.pattern] = []
                groups.append((route.pattern, group_map[route.pattern]))
            group_map[route.pattern].append(route)

        for pattern, chain in groups:
            for idx, route in enumerate(chain):
                seq = route.sequence
                if idx == 0:
                    lines.append("exten => %s,1,NoOp(Outbound: %s)" % (pattern, route.name))
                else:
                    lines.append(
                        "same => n(r%s-start),NoOp(Outbound: %s)" % (seq, route.name)
                    )
                if idx + 1 < len(chain):
                    next_label = "r%s-start" % chain[idx + 1].sequence
                else:
                    next_label = "%s,failover,1" % failover_ctx
                gate = self._route_time_gate(route, "r%s-go" % seq, next_label)
                if gate:
                    lines.extend(gate)
                else:
                    lines.append("same => n,Goto(r%s-go)" % seq)
                strip = route.strip_digits or 0
                num = "${EXTEN}" if not strip else "${EXTEN:%d}" % strip
                dial_number = "%s%s" % (route.prepend_digits or "", num)
                lines.append(
                    "same => n(r%s-go),Set(DIAL_NUMBER=%s)" % (seq, dial_number)
                )
                trunks = route.trunk_ids.sorted("sequence")
                for tidx, rt in enumerate(trunks):
                    lines.append(
                        "same => n,Dial(PJSIP/${DIAL_NUMBER}@%s-trunk-%s,60,tT)"
                        % (domain, self._slug(rt.trunk_id.name))
                    )
                    lines.append(
                        'same => n,GotoIf($["${DIALSTATUS}" = "ANSWER"]?%s,hangup,1)'
                        % failover_ctx
                    )
                    if tidx + 1 < len(trunks):
                        if rt.continue_:
                            lines.append("same => n,Goto(r%s-t%d)" % (seq, tidx + 1))
                        else:
                            lines.append(
                                "same => n,Goto(%s,failover,1)" % failover_ctx
                            )
                        lines.append(
                            "same => n(r%s-t%d),NoOp(Trunk failover to next)"
                            % (seq, tidx + 1)
                        )
                    else:
                        lines.append("same => n,Goto(%s,failover,1)" % failover_ctx)

        # Shared failover context: every trunk/route failed
        failover = self._outbound_failover(self.env, routes)
        lines.append("")
        lines.append("[%s]" % failover_ctx)
        lines.append("exten => failover,1,NoOp(All trunks failed)")
        lines.append("same => n,%s" % failover)
        lines.append("exten => hangup,1,Hangup()")
        return "\n".join(lines)

    def _route_time_gate(self, route, match_label, miss_label):
        """Return dialplan lines gating a route by time, or [] if ungated.

        Holidays (resource.calendar.leaves) always skip to miss_label;
        attendance/time-condition matches jump to match_label.
        """
        if (
            route.time_source == "time_condition"
            and "time_condition_id" in route._fields
            and route.time_condition_id
        ):
            tc = route.time_condition_id
            lines = self._holiday_skip_lines(tc.holidays_calendar_id, miss_label)
            lines.append(
                "same => n,GotoIfTime(%s-%s,%s,*,*?%s)"
                % (
                    self._format_time(tc.start_time),
                    self._format_time(tc.end_time),
                    tc.days_of_week,
                    match_label,
                )
            )
            lines.append("same => n,Goto(%s)" % miss_label)
            return lines
        if route.time_source == "calendar" and route.calendar_id:
            cal = route.calendar_id
            lines = self._holiday_skip_lines(cal, miss_label)
            for att in cal.attendance_ids.sorted("dayofweek"):
                lines.append(
                    "same => n,GotoIfTime(%s-%s,%s,*,*?%s)"
                    % (
                        self._format_time(att.hour_from),
                        self._format_time(att.hour_to),
                        _DAY_NAMES[int(att.dayofweek)],
                        match_label,
                    )
                )
            lines.append("same => n,Goto(%s)" % miss_label)
            return lines
        return []

    @staticmethod
    def _holiday_skip_lines(calendar, miss_label):
        """GotoIfTime per leave day — holidays skip to miss_label."""
        lines = []
        if not calendar:
            return lines
        for leave in calendar.leave_ids:
            d_from = leave.date_from.date()
            d_to = leave.date_to.date()
            d = d_from
            while d <= d_to:
                lines.append(
                    "same => n,GotoIfTime(00:00-23:59,%d,%d,%d?%s)"
                    % (d.day, d.month, d.year, miss_label)
                )
                d += timedelta(days=1)
        return lines

    @staticmethod
    def _outbound_failover(env, routes):
        """Dialplan executed when every route/trunk fails.

        Uses the last route's failover destination; otherwise congestion.
        """
        last = routes[-1]
        if last.failover_destination_id:
            return env["pbx.destination.mixin"]._render_destination(
                last.failover_destination_id
            )
        return "Playback(all-circuits-busy-now&please-try-call-later)"

    # ------------------------------------------------------------------
    # voicemail.conf
    # ------------------------------------------------------------------
    def generate_voicemail(self, domain, company):
        """Generate voicemail.conf for the instance."""
        extensions = self.env["pbx.extension"].search(
            [("company_id", "=", company), ("active", "=", True)]
        )
        mailboxes = []
        for ext in extensions:
            voicemail_sub = ext.sub_extension_ids.filtered(
                lambda s: s.active and s.type == "voicemail"
            )
            if voicemail_sub:
                sub = voicemail_sub[0]
                mailboxes.append(
                    MAILBOX_TEMPLATE.format(
                        public_number=ext.public_number,
                        pin=ext.public_number,  # Default PIN = extension number
                        callerid_name=ext.callerid_name or ext.user_id.name or "",
                        max_messages=sub.max_messages,
                        max_duration=sub.max_duration,
                    )
                )

        return VOICEMAIL_CONF_TEMPLATE.format(
            domain=domain,
            mailboxes="\n".join(mailboxes) if mailboxes else "",
        )

    def _get_plugin_recordsets(self):
        """Yield one recordset per concrete model implementing pbx.plugin.

        pbx.plugin is an AbstractModel with no table — plugins must be
        collected by scanning the registry for models inheriting it.
        """
        for model_name, model in self.env.registry.items():
            if model._abstract:
                continue
            inherits = model._inherit or []
            if isinstance(inherits, str):
                inherits = [inherits]
            if "pbx.plugin" in inherits:
                yield self.env[model_name]

    # ------------------------------------------------------------------
    # Orchestration
    # ------------------------------------------------------------------
    def _availability_gates(self, ext, company):
        """CURL check of Odoo availability before follow-me ringing.

        Only emitted when the extension respects schedule/calendar AND an Odoo
        URL is configured. The endpoint returns ``ok:<ts>`` or ``busy:<ts>``;
        on CURL failure the variable is empty → the call proceeds (fail-open).
        """
        if not (ext.respect_schedule or ext.respect_calendar):
            return ""
        if isinstance(company, models.Model):
            company_rec = company
        else:
            company_rec = self.env["res.company"].browse(company)
        odoo_url = company_rec.pbx_odoo_url or self.env["ir.config_parameter"].get_param(
            "web.base.url", ""
        )
        if not odoo_url:
            return ""
        token = self.env["ir.config_parameter"].get_param("pbx.webhook.token", "")
        return ext._render_availability_gate(odoo_url=odoo_url, webhook_token=token)

    def _availability_announcement(self, domain, public_number, active=False):
        """Label block reached via the availability gate when unavailable."""
        if not active:
            return ""
        return AVAILABILITY_ANNOUNCEMENT_TEMPLATE.format(
            domain=domain, public_number=public_number
        )

    def generate_all(self, domain, company):
        """Generate all config files for the instance, incl. plugin snippets."""
        configs = {
            "pjsip_wizard.conf": self.generate_pjsip(domain, company),
            "extensions.conf": self.generate_extensions(domain, company),
            "voicemail.conf": self.generate_voicemail(domain, company),
        }

        # Collect plugin snippets
        for plugin in self._get_plugin_recordsets():
            snippets = plugin.get_config_snippets(domain, company)
            for filename, content in snippets.items():
                if filename in configs:
                    configs[filename] += "\n" + content
                else:
                    configs[filename] = content

        return configs

    def write_config(self, domain, company):
        """Deploy generated config to the Asterisk server via RabbitMQ.

        The pbx_ami_daemon consumes `pbx.config.<domain>` and writes the
        files to /etc/asterisk/tenants/ then reloads Asterisk.
        """
        configs = self.generate_all(domain, company)
        mq = self.env["pbx.mq.publisher"]
        if mq.publish_config(domain, configs):
            _logger.info("Deployed config via MQ for domain %s", domain)
            return True
        _logger.warning("MQ not configured — config not deployed for %s", domain)
        return False

    def get_sync_state(self):
        """Current sync state for the user's company (used by the systray)."""
        company = self.env.company
        return {
            "dirty": bool(company.config_dirty),
            "domain": company.pbx_domain or "",
        }

    def sync_current_company(self):
        """Deploy config for the current user's company to Asterisk.

        Returns a dict with ok/message for the UI notification. Marks the
        company clean on success.
        """
        company = self.env.company
        domain = company.pbx_domain
        if not domain:
            return {
                "ok": False,
                "message": "Ingen SIP-domän satt för företaget (Settings → PBX).",
            }
        ok = self.write_config(domain, company)
        if ok:
            company.config_dirty = False
            return {
                "ok": True,
                "message": "Konfiguration skickad till Asterisk för %s." % domain,
            }
        return {
            "ok": False,
            "message": "Konfigurationen kunde inte skickas (%s) — kontrollera RabbitMQ-inställningarna."
            % domain,
        }
