# Copyright 2026 Vertel AB
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import _, api, fields, models
from odoo.exceptions import UserError


class PbxConference(models.Model):
    _name = "pbx.conference"
    _inherit = ["pbx.plugin", "pbx.destination.mixin", "mail.thread", "mail.activity.mixin"]
    _description = "PBX Conference Room"

    name = fields.Char(required=True, help="e.g. Ledningsmöte")
    extension = fields.Char(required=True, help="Internal extension for the conference")
    pin = fields.Char(help="PIN code for participants")
    admin_pin = fields.Char(help="Admin PIN (moderator)")
    max_participants = fields.Integer(default=10)
    record = fields.Boolean(default=False, help="Record conference?")
    active = fields.Boolean(default=True)
    company_id = fields.Many2one(
        "res.company", default=lambda self: self.env.company, required=True
    )

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get("extension"):
                company = (
                    self.env["res.company"].browse(vals["company_id"])
                    if vals.get("company_id")
                    else self.env.company
                )
                if company:
                    self.env["pbx.numbering"]._check_dialable_number(
                        company, vals["extension"]
                    )
        return super().create(vals_list)

    def write(self, vals):
        if vals.get("extension"):
            for rec in self:
                self.env["pbx.numbering"]._check_dialable_number(
                    rec.company_id, vals.get("extension", rec.extension), exclude=rec
                )
        return super().write(vals)

    def get_internal_dialplan(self, domain, company):
        """Make conference rooms reachable by their internal extension number."""
        lines = []
        conferences = self.search(
            [("company_id", "=", company.id), ("active", "=", True)]
        )
        for conf in conferences:
            lines.append(
                "exten => %s,1,Goto(%s-conf-%s,s,1)"
                % (conf.extension, domain, self._slug(conf.name))
            )
        return "\n".join(lines)

    def action_next_free_extension(self):
        """Föreslå nästa lediga nummer i konferensserien (6xx)."""
        self.ensure_one()
        number = self.env["pbx.numbering"]._next_free_service_number(
            self.company_id, "conference"
        )
        if not number:
            raise UserError(_("Inga lediga nummer i konferensserien."))
        self.extension = number
        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": _("Nästa lediga"),
                "message": _("Föreslår %s") % number,
                "type": "success",
                "sticky": False,
            },
        }

    def get_dialplan_target(self):
        self.ensure_one()
        return ("%s-conf-%s" % (self.company_id.pbx_domain, self._slug(self.name)), "s", "1")

    @staticmethod
    def _slug(name):
        return (name or "").lower().replace(" ", "-")

    def get_config_snippets(self, domain, company):
        conferences = self.search([("company_id", "=", company.id), ("active", "=", True)])
        if not conferences:
            return {}
        return {
            "confbridge.conf": self._generate_confbridge_conf(conferences),
            "extensions_conference.conf": self._generate_conference_dialplan(conferences),
        }

    def _generate_conference_dialplan(self, conferences):
        """Per-conference originate context (Operator Panel click-to-join).

        Redirect/Originate to Context=<domain>-conf-<name>, Exten=s.
        """
        lines = [f"; Auto-generated by pbx_conference — domain: {domain}"]
        for conf in conferences:
            name = conf.name.lower().replace(" ", "-")
            lines.append(f"\n[{domain}-conf-{name}]")
            lines.append(f"exten => s,1,ConfBridge({domain}-{name},{domain}-{name}-user)")
        return "\n".join(lines)

    def _generate_confbridge_conf(self, conferences):
        lines = [f"; Auto-generated by pbx_conference — domain: {domain}"]
        for conf in conferences:
            name = conf.name.lower().replace(" ", "-")
            lines.append(f"\n[{domain}-{name}]")
            lines.append("type = bridge")
            lines.append(f"max_members = {conf.max_participants}")
            lines.append(f"record_conference = {'yes' if conf.record else 'no'}")

            lines.append(f"\n[{domain}-{name}-user]")
            lines.append("type = user")
            if conf.pin:
                lines.append(f"pin = {conf.pin}")
            if conf.admin_pin:
                lines.append(f"admin_pin = {conf.admin_pin}")
            lines.append("marked = no")
            lines.append("wait_marked = no")
            lines.append("quiet = no")
            lines.append("announce_user_count = yes")
        return "\n".join(lines)

    def get_operator_panel_widgets(self):
        widgets = []
        confs = self.search(
            [("company_id", "=", self.env.user.company_id.id), ("active", "=", True)]
        )
        for conf in confs:
            widgets.append(
                {
                    "name": f"conference_panel_{conf.id}",
                    "component": "PbxConferencePanel",
                    "props": {
                        "conference": {
                            "key": conf.extension,
                            "name": conf.name,
                            "has_pin": bool(conf.pin),
                        }
                    },
                }
            )
        return widgets
