# Copyright 2026 Vertel AB
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import api, fields, models


class PbxConference(models.Model):
    _name = "pbx.conference"
    _inherit = ["pbx.plugin", "pbx.destination.mixin"]
    _description = "PBX Conference Room"

    tenant_id = fields.Many2one("pbx.tenant", required=True, ondelete="cascade")
    name = fields.Char(required=True, help="e.g. Ledningsmöte")
    extension = fields.Char(required=True, help="Internal extension for the conference")
    pin = fields.Char(help="PIN code for participants")
    admin_pin = fields.Char(help="Admin PIN (moderator)")
    max_participants = fields.Integer(default=10)
    record = fields.Boolean(default=False, help="Record conference?")
    active = fields.Boolean(default=True)
    company_id = fields.Many2one(related="tenant_id.company_id", store=True)

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get("extension"):
                company = self._company_from_vals(vals)
                if company:
                    self.env["pbx.numbering"]._check_dialable_number(
                        company, vals["extension"]
                    )
        return super().create(vals_list)

    def write(self, vals):
        if vals.get("extension") or vals.get("tenant_id"):
            for rec in self:
                tenant = (
                    self.env["pbx.tenant"].browse(vals["tenant_id"])
                    if vals.get("tenant_id")
                    else rec.tenant_id
                )
                company = tenant.company_id if tenant else rec.company_id
                number = vals.get("extension", rec.extension)
                self.env["pbx.numbering"]._check_dialable_number(
                    company, number, exclude=rec
                )
        return super().write(vals)

    def _company_from_vals(self, vals):
        """Company från tenant_id i vals (pbx.tenant lever i pbx_admin)."""
        tenant_id = vals.get("tenant_id")
        if tenant_id and "pbx.tenant" in self.env:
            tenant = self.env["pbx.tenant"].browse(tenant_id)
            return tenant.company_id
        return False

    def get_internal_dialplan(self, tenant):
        """Make conference rooms reachable by their internal extension number."""
        lines = []
        conferences = self.search(
            [("tenant_id", "=", tenant.id), ("active", "=", True)]
        )
        for conf in conferences:
            lines.append(
                "exten => %s,1,Goto(%s-conf-%s,s,1)"
                % (conf.extension, tenant.domain, self._slug(conf.name))
            )
        return "\n".join(lines)

    def get_dialplan_target(self):
        self.ensure_one()
        return ("%s-conf-%s" % (self.tenant_id.domain, self._slug(self.name)), "s", "1")

    @staticmethod
    def _slug(name):
        return (name or "").lower().replace(" ", "-")

    def get_config_snippets(self, tenant):
        conferences = self.search([("tenant_id", "=", tenant.id), ("active", "=", True)])
        if not conferences:
            return {}
        return {
            "confbridge.conf": self._generate_confbridge_conf(conferences),
            "extensions_conference.conf": self._generate_conference_dialplan(conferences),
        }

    def _generate_conference_dialplan(self, conferences):
        """Per-conference originate context (Operator Panel click-to-join).

        Redirect/Originate to Context=<domain>-conf-<name>, Exten=s.
        """
        domain = conferences[0].tenant_id.domain
        lines = [f"; Auto-generated by pbx_conference — tenant: {domain}"]
        for conf in conferences:
            name = conf.name.lower().replace(" ", "-")
            lines.append(f"\n[{domain}-conf-{name}]")
            lines.append(f"exten => s,1,ConfBridge({domain}-{name},{domain}-{name}-user)")
        return "\n".join(lines)

    def _generate_confbridge_conf(self, conferences):
        domain = conferences[0].tenant_id.domain
        lines = [f"; Auto-generated by pbx_conference — tenant: {domain}"]
        for conf in conferences:
            name = conf.name.lower().replace(" ", "-")
            lines.append(f"\n[{domain}-{name}]")
            lines.append("type = bridge")
            lines.append(f"max_members = {conf.max_participants}")
            lines.append(f"record_conference = {'yes' if conf.record else 'no'}")

            lines.append(f"\n[{domain}-{name}-user]")
            lines.append("type = user")
            if conf.pin:
                lines.append(f"pin = {conf.pin}")
            if conf.admin_pin:
                lines.append(f"admin_pin = {conf.admin_pin}")
            lines.append("marked = no")
            lines.append("wait_marked = no")
            lines.append("quiet = no")
            lines.append("announce_user_count = yes")
        return "\n".join(lines)

    def get_operator_panel_widgets(self):
        widgets = []
        confs = self.search(
            [("company_id", "=", self.env.user.company_id.id), ("active", "=", True)]
        )
        for conf in confs:
            widgets.append(
                {
                    "name": f"conference_panel_{conf.id}",
                    "component": "PbxConferencePanel",
                    "props": {
                        "conference": {
                            "key": conf.extension,
                            "name": conf.name,
                            "has_pin": bool(conf.pin),
                        }
                    },
                }
            )
        return widgets
