# Copyright 2026 Vertel AB
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import fields, models


class PbxConference(models.Model):
    _name = "pbx.conference"
    _inherit = ["pbx.plugin"]
    _description = "PBX Conference Room"

    tenant_id = fields.Many2one("pbx.tenant", required=True, ondelete="cascade")
    name = fields.Char(required=True, help="e.g. Ledningsmöte")
    extension = fields.Char(required=True, help="Internal extension for the conference")
    pin = fields.Char(help="PIN code for participants")
    admin_pin = fields.Char(help="Admin PIN (moderator)")
    max_participants = fields.Integer(default=10)
    record = fields.Boolean(default=False, help="Record conference?")
    active = fields.Boolean(default=True)
    company_id = fields.Many2one(related="tenant_id.company_id", store=True)

    def get_config_snippets(self, tenant):
        conferences = self.search([("tenant_id", "=", tenant.id), ("active", "=", True)])
        if not conferences:
            return {}
        return {"confbridge.conf": self._generate_confbridge_conf(conferences)}

    def _generate_confbridge_conf(self, conferences):
        domain = conferences[0].tenant_id.domain
        lines = [f"; Auto-generated by pbx_conference — tenant: {domain}"]
        for conf in conferences:
            name = conf.name.lower().replace(" ", "-")
            lines.append(f"\n[{domain}-{name}]")
            lines.append("type = bridge")
            lines.append(f"max_members = {conf.max_participants}")
            lines.append(f"record_conference = {'yes' if conf.record else 'no'}")

            lines.append(f"\n[{domain}-{name}-user]")
            lines.append("type = user")
            if conf.pin:
                lines.append(f"pin = {conf.pin}")
            if conf.admin_pin:
                lines.append(f"admin_pin = {conf.admin_pin}")
            lines.append("marked = no")
            lines.append("wait_marked = no")
            lines.append("quiet = no")
            lines.append("announce_user_count = yes")
        return "\n".join(lines)

    def get_fop2_widgets(self):
        return [{"name": "conference_panel", "component": "PbxConferencePanel", "props": {}}]
